### ISSUE TITLE
Investigate flow of files from previously-source-built packages to determine if/how files leak

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1443] opened 2020-01-14 21:11 UTC
- Possibly related to `<RestoreFallbackFolders>$(PackagesDir)</RestoreFallbackFolders>` in core-setup
- We should probably be poisoning previously-source-built files now that actual prebuilts are gone

**Comment by dagood** [comment] 2020-02-13 19:51
Duplicate of #1454

**Closed by dagood** 2020-02-13 19:51 UTC
