### ISSUE TITLE
5.0 RTM isn't tagged

### ISSUE THREAD

**Issue by azixaka** [dotnet/source-build#1913] opened 2020-11-23 18:15 UTC

**Comment by azixaka** [comment] 2020-11-23 18:16
@tmds @RheaAyase

**Comment by omajid** [comment] 2020-11-23 18:25
Duplicate of https://github.com/dotnet/source-build/issues/1891?

**Comment by dagood** [comment] 2020-11-23 18:39
Yeah, we don't have `v5.0.100-SDK`/`v5.0.0-runtime` tags because we don't have it done yet. (If you install ZenHub, you should be able to see remaining issues in https://github.com/dotnet/source-build/issues/1891.)

There's also an end-user-facing issue tracking this here: [**.NET 5 is missing in RHEL (CentOS) & Fedora** dotnet/core#5596](https://github.com/dotnet/core/issues/5596)

Closing as duplicate.

**Closed by dagood** 2020-11-23 18:39 UTC
