### ISSUE TITLE
Ubuntu2204_Offline_MsftSdk_x64 failing due to time out

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4380] opened 2024-05-07 11:53 UTC
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2446519&view=logs&j=2ba1d9ec-c64c-5aa0-fa6f-34087e58be0f&t=17bd3bf0-ddd7-5a6d-ce00-002f452f5cb4

Error:

      [FAIL] Microsoft.DotNet.ScenarioTests.SdkTemplateTests.SdkTemplateTests.VerifyWebTemplate(language: CSharp)
      System.InvalidOperationException :  /vmr/artifacts/obj/extracted-dotnet-sdk/dotnet run /bl:/vmr/artifacts/scenario-tests/artifacts/SdkTemplateTest_Web_CSharp/run.binlog timed out after 30000 milliseconds
      Exit code: 137
         at Microsoft.DotNet.ScenarioTests.Common.ExecuteHelper.ExecuteProcess(String fileName, String args, ITestOutputHelper outputHelper, Boolean logOutput, Action`1 configure, Int32 millisecondTimeout) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.Common/ExecuteHelper.cs:line 71
         at Microsoft.DotNet.ScenarioTests.SdkTemplateTests.DotNetSdkHelper.ExecuteCmdImpl(String args, String workingDirectory, Action`1 additionalProcessConfigCallback, Int32 expectedExitCode, Int32 millisecondTimeout) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs:line 42
         at Microsoft.DotNet.ScenarioTests.SdkTemplateTests.DotNetSdkHelper.ExecuteCmd(String args, String workingDirectory, Action`1 additionalProcessConfigCallback, Int32 expectedExitCode, Int32 millisecondTimeout) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs:line 37
         at Microsoft.DotNet.ScenarioTests.SdkTemplateTests.DotNetSdkHelper.ExecuteRunWeb(String projectDirectory) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/DotNetSdkHelper.cs:line 175
         at Microsoft.DotNet.ScenarioTests.SdkTemplateTests.SdkTemplateTest.Execute(DotNetSdkHelper dotNetHelper, String testRoot, String[] frameworks, String PreMadeSolution) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTest.cs:line 71
         at Microsoft.DotNet.ScenarioTests.SdkTemplateTests.SdkTemplateTests.VerifyWebTemplate(DotNetLanguage language) in /_/src/scenario-tests/src/Microsoft.DotNet.ScenarioTests.SdkTemplateTests/SdkTemplateTests.cs:line 187
      
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
      Finished Microsoft.DotNet.ScenarioTests.SdkTemplateTests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
      
      Tests run: 30, Errors: 0, Failures: 1, Skipped: 0. Time: 649.6365527s

**Comment by mthalman** [comment] 2024-05-07 13:28
Duplicate of https://github.com/dotnet/source-build/issues/4372. A fix is merged and will roll out.

**Closed** 2024-05-07 20:02 UTC
Labels: untriaged, ops-monitor
