### ISSUE TITLE
stage 2 build fails with api compat issues during runtime build

### ISSUE THREAD

**Issue by tmds** [dotnet/source-build#3684] opened 2023-10-24 17:57 UTC
Our CI does a stage 2 build, and this build is failing with the following error during the runtime build:
```
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-rtm.23520.55/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : API compatibility errors between 'ref/net8.0/System.Private.CoreLib.dll' (left) and 'lib/net8.0/System.Private.CoreLib.dll' (right): [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-rtm.23520.55/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error CP0001: Type 'System.Diagnostics.DebuggerGuidedStepThroughAttribute' exists on lib/net8.0/System.Private.CoreLib.dll but not on ref/net8.0/System.Private.CoreLib.dll [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-rtm.23520.55/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error CP0001: Type 'System.Runtime.CompilerServices.EagerStaticClassConstructionAttribute' exists on lib/net8.0/System.Private.CoreLib.dll but not on ref/net8.0/System.Private.CoreLib.dll [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /home/tester/dotnet/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-rtm.23520.55/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : API breaking changes found. If those are intentional, the APICompat suppression file can be updated by rebuilding with '/p:ApiCompatGenerateSuppressionFile=true' [/home/tester/dotnet/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
```

The job was successful with https://github.com/dotnet/dotnet/commit/265cc107038e62ca66c4010cc3a029c86b5d812d, and fails with https://github.com/dotnet/dotnet/commit/49a6dcc2b815c1aa1ee14fef4ca2f3b6ba05f8ab.

These types are in https://github.com/dotnet/runtime/blob/release/8.0/eng/ApiCompatExcludeAttributes.txt#L2-L3, so they should probably be ignored during the api compat check.

cc @MichaelSimons @omajid

**Comment by mthalman** [comment] 2023-10-24 17:59
This is a duplicate of https://github.com/dotnet/runtime/issues/93867. It's been fixed, but the fix hasn't flowed to the VMR yet.

**Closed** 2023-10-24 18:12 UTC
Labels: untriaged
