### ISSUE TITLE
Poison marker failure for xunit.abstractions.2.0.3

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3657] opened 2023-10-12 13:52 UTC
As a result of the changes from https://github.com/dotnet/installer/pull/17498, the following error occurs when attempting to set poison markers in the Fedora build leg of the VMR:

```
/vmr/eng/tools/init-build.proj(154,5): error MSB4018: The "MarkAndCatalogPackages" task failed unexpectedly.
/vmr/eng/tools/init-build.proj(154,5): error MSB4018: System.ArgumentException: Marker file name '.source-built.xml' is not sufficiently unique!  Exists in '/vmr/prereqs/packages/previously-source-built/xunit.abstractions.2.0.3.nupkg'. (Parameter 'MarkerFileName')
/vmr/eng/tools/init-build.proj(154,5): error MSB4018:    at Microsoft.DotNet.SourceBuild.Tasks.LeakDetection.MarkAndCatalogPackages.Execute() in /vmr/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/MarkAndCatalogPackages.cs:line 138
/vmr/eng/tools/init-build.proj(154,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/vmr/eng/tools/init-build.proj(154,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

[Related build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2289383) (internal only)

**Comment by MichaelSimons** [comment] 2023-10-12 14:12
I suspect this is fallout from adding xunit.abstractions to SBRP.  If so, this would be fixed with https://github.com/dotnet/source-build-reference-packages/commit/158cb6e53557ed53338449b51e16e399c8d4a2f4 which just flowed in https://github.com/dotnet/dotnet/commit/1754673b6a57d561f6a2befa2d79e5b0d061fa39

**Comment by MichaelSimons** [comment] 2023-10-12 14:13
The problem is likely related to this version existing is PSB.

**Comment by NikolaMilosavljevic** [comment] 2023-10-13 01:22
We need a fix for this. There are two copies of `xunit.abstractions` in PSB archive - one is the psb package, the other is the sbrp. Poison infra extracts to a temporary folder named after package identity, and doesn't clean package-specific content after repackaging it. When second package with the same exact identity is extracted to the same folder, there will already be the marker file and infra would fail, thinking that the marker is part of package contents.

The solution would be to clean temporary folders as soon as they're not needed anymore. Working on a fix.

**Comment by NikolaMilosavljevic** [comment] 2023-10-13 18:32
Fixed with https://github.com/dotnet/installer/pull/17527

**Closed by NikolaMilosavljevic** 2023-10-13 18:32 UTC
Labels: area-ci-testing
