### ISSUE TITLE
License scan is failing for sdk repo

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4346] opened 2024-04-22 08:56 UTC
`main` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2435523&view=logs&j=6743a87c-2e18-5ff9-0f6c-56bd82018320&t=6b957730-76c5-5b5b-c7fc-7fc79d5ee5c5

    {
      "files": [
        {
          "path": "src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs",
          "detected_license_expression": "mit AND unknown-license-reference AND (apache-1.1 AND apache-2.0 AND llvm-exception AND apsl-2.0) AND (boost-1.0 AND bsd-new AND bsd-original-uc AND bsd-simplified AND cc0-1.0 AND cc-by-3.0 AND cc-by-4.0 AND cc-by-sa-3.0 AND cc-by-sa-4.0 AND epl-1.0 AND gpl-1.0 AND gpl-2.0 AND gpl-2.0-plus AND isc AND lgpl-2.0 AND lgpl-2.1 AND lgpl-2.1-plus AND mit AND ms-pl AND ms-rl AND ngpl AND ofl-1.1 AND public-domain AND python AND rpl-1.5 AND sax-pd AND unicode AND w3c AND x11-xconsortium AND zlib) AND (mit OR apache-2.0)"
        },
        {
          "path": "src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseExclusions.txt",
          "detected_license_expression": "cecill-c AND (cecill-c AND proprietary-license) AND proprietary-license AND llvm-exception"
        },
        {
          "path": "src/VirtualMonoRepo/THIRD-PARTY-NOTICES.template.txt",
          "detected_license_expression": "unknown-license-reference"
        }
      ]
    }

More detail: [scancode-results.json](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQzNTUyMy9hcnRpZmFjdE5hbWUvTGljZW5zZVNjYW4rc2RrX0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fartifacts%2FTestResults%2FRelease%2Fscancode-results.json)

**Comment by MichaelSimons** [comment] 2024-04-22 14:37
Oh how ironic that the test is failing on itself 🤣  

This is caused by the current work going onto consolidate the sdk and installer repos.

**Comment by mthalman** [comment] 2024-04-22 15:57
> Oh how ironic that the test is failing on itself 🤣

![Alt Text](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzR2MzBoNDJ6NGJ6dXlqbXpqbWwyc2dmenl1aTluMHVqZWpnM3JidCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xThuWu82QD3pj4wvEQ/giphy.gif)

**Comment by MichaelSimons** [comment] 2024-05-02 16:56
[Triage] This will be resolved when the sdk->installer merge is complete.

**Comment by MichaelSimons** [comment] 2024-05-08 20:32
This was resolved with the sdk-installer merge.

**Closed by MichaelSimons** 2024-05-08 20:32 UTC
Labels: area-testing, ops-monitor
