### ISSUE TITLE
Automate source-build release process for 6.0 and 7.0

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3065] opened 2022-10-13 00:39 UTC
### Describe the Problem

The source-build release process takes up a lot of time. Also, many of the release tasks are completed manually which leaves lots of room for individual error.

### Describe the Solution

The current release process is documented here: https://github.com/dotnet/source-build/blob/3c8f23d08475e6f59a5ca889e0719b61e18db476/.github/ISSUE_TEMPLATE/releases/release_checklist.md

The large majority of those release tasks should be automated. We can break this up into pipelines that can be run during different parts of the release cycle. I am proposing that we expand the current [source-build-release pipeline](https://github.com/dotnet/source-build/blob/3c8f23d08475e6f59a5ca889e0719b61e18db476/eng/source-build-release.yml) and create a new pipeline, **source-build-pre-release**.

`source-build-pre-release` (in order of execution, not priority):
- https://github.com/dotnet/source-build/issues/2710
- https://github.com/dotnet/source-build/issues/3068
- https://github.com/dotnet/source-build/issues/3064
- https://github.com/dotnet/source-build/issues/3069
- https://github.com/dotnet/source-build/issues/2904

In between `pre-release` and `release`, after security-partners-dotnet PRs are merged:
- https://github.com/dotnet/source-build/issues/3147
- https://github.com/dotnet/source-build/issues/3179
- https://github.com/dotnet/source-build/issues/3196

`source-build-release`:

- https://github.com/dotnet/source-build/issues/3080
- https://github.com/dotnet/source-build/issues/3062
- https://github.com/dotnet/source-build/issues/2888
- https://github.com/dotnet/source-build/issues/3058

**Comment by lbussell** [comment] 2022-10-13 17:45
In terms of priority, I see the following as most important:

- #3064: Updating the VMR-lite is done manually and prone to individual error
- #2904: We currently only manually test the VMR-lite

Everything else is fairly well defined, just manual work.

**Comment by MichaelSimons** [comment] 2022-10-13 19:16
@lbussell - where does #2921 fit in here?  Is it a duplicate of 3096?

**Comment by premun** [comment] 2023-03-09 16:04
The remaining open items are still relevant and I am not sure I'll have time to work on those so this might make sense to keep for tracking?

**Closed** 2023-03-09 17:09 UTC
Labels: area-infra, untriaged
