### ISSUE TITLE
dotnet/sdk needs to build for net472 during source-build

### ISSUE THREAD

**Issue by eerhardt** [dotnet/source-build#2548] opened 2021-10-21 17:22 UTC
In order for OmniSharp to work with a source-built .NET SDK, we need to build our MSBuild tasks for netfx. This is because OmniSharp uses Mono. For example, see https://github.com/dotnet/source-build/issues/2006.

In 5.0, we built the SDK tasks for netfx. But in https://github.com/dotnet/sdk/pull/19649 we stripped the netfx TFM during the build.

@MichaelSimons @crummel @dagood @dseefeld

**Comment by lambdageek** [comment] 2022-01-03 21:24
(Not sure if this is the same underlying issue, but I think it is)

 
Another symptom is that OmniSharp may fail to load some analyzers such as https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/TypesShouldNotExtendCertainBaseTypes.cs
because Microsoft.CodeAnalysis.NetAnalyzers.dll  from source build references System.Collections.Immutable.dll version 6.0, whereas the official SDK NetAnalyzers.dll references System.Collections.Immutable.dll version 1.2.3.0.

As a result during O# initialization Mono may print errors such as:

```
Failure while loading the analyzer reference 'Microsoft.CodeAnalysis.NetAnalyzers': Type Microsoft.NetFramework.Analyzers.TypesShouldNotExtendCertainBaseTypesAnalyzer has invalid vtable method slot 5 with method none
```

(The issue is that the type of the `DiagnosticAnalyzer.SupportedDiagnostics` property is `ImmutableArray<DiagnosticDescriptor>` where `ImmutableArray<>` comes from System.Collections.Immutable.  Since the NetAnalyzers.dll wants a newer version of System.Collections.Immutable than what comes with OmniSharp/mono, the class initialization fails and Mono prints this unhelpful error message).

/cc @webczat

**Comment by MichaelSimons** [comment] 2022-02-01 19:53
@lambdageek - can you please log a separate issue for the OmniSharp issue you encountered?

**Comment by MichaelSimons** [comment] 2022-02-01 19:54
Closing this as the patch was backported - https://github.com/dotnet/sdk/pull/23266

**Closed by MichaelSimons** 2022-02-01 19:54 UTC
Labels: area-additional-repos

**Comment by webczat** [comment] 2022-02-01 19:55
I think we confirmed it was exactly that issue.
