### ISSUE TITLE
Error when sending partner email

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4710] opened 2024-10-30 19:31 UTC
An SMTP error occurred from the notification pipeline when attempting to send the partner email. See the [build log](https://dev.azure.com/dnceng/internal/_build/results?buildId=2571895&view=logs&j=f016dffd-d56f-5421-9b3d-72ee169d87b3&t=9f989238-bac2-5d56-4df3-54829ae6c8f9) (internal link) for more details.

**Comment by MichaelSimons** [comment] 2024-10-31 16:44
@oleksandr-didyk - Can you take a look at this failure?  It appears auth related.

**Comment by mthalman** [comment] 2024-11-01 15:09
This may have been a temporary issue. The [pipeline run for the .NET 9 release](https://dev.azure.com/dnceng/internal/_build/results?buildId=2573276&view=results) (internal link) succeeded with sending email.

**Comment by oleksandr-didyk** [comment] 2024-11-12 13:40
Sorry for a delayed response, I somehow managed to miss the email notification

It does look like an auth issue, but at that point in time the secret was (and still is) valid. Additionally, we are not the only ones using it so there would be failures across the board, but I could not find any notices or complains during the time the pipeline was run. There were similar issues a month ago caused by the secret expiring, but they were resolved way before the pipeline was started so it should have used the new valid value

As Matt mentioned, this does look like some temporary issue. We could keep the issue opened for 1 or 2 more runs just to track if it comes back

**Comment by MichaelSimons** [comment] 2024-11-12 14:47
We should proactively close this and reopen if the issue re-occurs.  There is no value in leaving it open when there is no action to take.

**Closed by MichaelSimons** 2024-11-12 14:47 UTC
Labels: area-release-infra
