### ISSUE TITLE
[main] CI build failure in CentOSStream9_Offline_x64 leg

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3202] opened 2023-01-09 17:29 UTC
There is currently a build failure in the CentOSStream9_Offline_x64 leg in [CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=2083096&view=logs&j=d43acb15-7fd3-5590-e766-047a2d0aa328&t=2917b4f5-5808-5de3-2de6-0590ccf0b931) (internal Microsoft link).  No Other CI leg is encountering this error.

```
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.DesktopStrongNameProvider.<>c__DisplayClass12_0.<SignBuilder>b__0(IEnumerable`1 content) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at System.Reflection.PortableExecutable.PEBuilder.Sign(BlobBuilder peImage, Blob strongNameSignatureFixup, Func`2 signatureProvider) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netstandard2.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Interop.Crypto.RsaSignHash(SafeEvpPKeyHandle pkey, RSASignaturePaddingMode paddingMode, IntPtr digestAlgorithm, ReadOnlySpan`1 hash, Span`1 destination) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at System.Security.Cryptography.RSAOpenSsl.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Boolean allocateSignature, Int32& bytesWritten, Byte[]& signature) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at System.Security.Cryptography.RSAOpenSsl.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.SigningUtilities.CalculateRsaSignature(IEnumerable`1 content, RSAParameters privateKey) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.DesktopStrongNameProvider.<>c__DisplayClass12_0.<SignBuilder>b__0(IEnumerable`1 content) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at System.Reflection.PortableExecutable.PEBuilder.Sign(BlobBuilder peImage, Blob strongNameSignatureFixup, Func`2 signatureProvider) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=netcoreapp3.0] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
    /vmr/src/source-build-reference-packages/artifacts/source-build/self/src/eng/SourceBuild.props(18,5): error MSB3073: The command "./build.sh --configuration Release /bl:/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/artifacts/sourcebuild-dependency-projects.binlog /p:LocalNuGetPackageCacheDirectory=/vmr/artifacts/obj/source-build-reference-package-cache /p:BuildDependencyPackageProjects=true /p:SetUpSourceBuildIntermediateNupkgCache=true /p:DotNetBuildFromSource=true /p:ArcadeInnerBuildFromSource=true" exited with code 1. [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
```

**Comment by omajid** [comment] 2023-01-09 17:31
This feels like https://github.com/dotnet/runtime/issues/65874. Is there an `OpenSslCryptographicException` in the log?

**Comment by MichaelSimons** [comment] 2023-01-11 23:44
Yes there is 

```
/vmr/.dotnet/sdk/8.0.100-alpha.1.22579.5/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.drawing.common/4.7.2/System.Drawing.Common.4.7.2.csproj::TargetFramework=net461] [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Build.proj]
```

**Comment by mthalman** [comment] 2023-01-13 19:58
So far I've verified that this is caused by a newer version of the Centos Stream 9 Docker image referenced in the pipeline: https://github.com/dotnet/dotnet/blob/46a1c2be501862fa56901c9c127d875750a37012/src/installer/eng/pipelines/templates/stages/vmr-build.yml#L17

For reference, the build for .NET 7 is successful because it uses an older version of the Docker image:
https://github.com/dotnet/installer/blob/1e15b09a1df5407ba921ac4212d1fdeadecbf215/src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml#L13

In addition, I also verified that setting `OPENSSL_ENABLE_SHA1_SIGNATURES=1` for the container does get rid of the error.

I'll investigate further to see what I can find about the difference between the two Docker image versions that caused this to occur.

**Comment by mthalman** [comment] 2023-01-13 21:30
I've identified that the regression occurred as a result of the difference between these two images:
* mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9-20220107135047-4cd394c
* mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9-20220420192933-4cd394c

I'll dig into those to see what I find for differences.

**Comment by omajid** [comment] 2023-01-13 21:58
CentOS Stream 9 is based on RHEL 9's development branch - it tracks what will release as the next minor update for RHEL 9.x.

The first image, based on the date, was built on/around 2022-01-07. RHEL 9.0 was released in May 2022. So the first Centos Stream 9 image is actually a snapshot of a pre-GA release of of a RHEL 9.

[This commit to OpenSSL 3.0 in CentOS Stream 9 (and in RHEL 9.0)](https://gitlab.com/redhat/centos-stream/rpms/openssl/-/commit/78fb78d30755ae18fdaef28ef392f4e67c662ff6) disabled SHA1 as a crypto algorithm in many (but not all) configurations. It was made in February 2022, so it was not present in the first container image. Strong naming needs SHA1, so with SHA1 disabled, it's broken. There's more details on the Strong Naming and CentOS Stream 9/RHEL 9 interaction at https://github.com/dotnet/runtime/issues/65874, including, I think our plan to eventually use PublicSigning by default when building .NET on non-Windows using source-build.

There's also https://github.com/dotnet/source-build/issues/2907 that's about getting source-build to use PublicSign everywhere.

**Closed** 2023-01-19 16:35 UTC
Labels: area-ci-testing, up-for-grabs
