### ISSUE TITLE
Design and implement a way for staging to know where an asset came from in the VMR build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3898] opened 2024-01-04 20:53 UTC
There is a non-trivial amount of automation in staging pipeline today the knows about where a particular component was build. For instance, sign checking will need to know where the asset it's looking at was built so as to find the sign check exclusion files. Similar goes for SDL validation, aka.ms link creation (to some degree), etc.

We should determine whether we can avoid this requirement altogether, or augment the VMR automation to record what component built what.

**T-Shirt Size: Medium**

**Comment by mmitche** [comment] 2024-01-04 20:54
@MilenaHristova

**Comment by tkapin** [comment] 2024-02-07 09:57
This is a prerequisite to other issues in the Release Infra area and should be figured out sooner than later. @mmitche - it's part of the VB area. Who do you see working on this, ideally?

**Comment by mmitche** [comment] 2024-02-07 15:51
Probably @NikolaMilosavljevic? i think this is in the general publishing bucket:

#4101

**Comment by andriipatsula** [comment] 2024-02-08 10:19
Plus, this issue is a prerequisite to https://github.com/dotnet/release/issues/783

**Comment by tkapin** [comment] 2024-02-15 14:00
@MichaelSimons - since this is a prerequisite for https://github.com/dotnet/release/issues/776, we need to get clarity of when this work will start and how can @andriipatsula and @MilenaHristova contribute to it so it doesn't become a blocker for the release infra UB tasks.

**Comment by mmitche** [comment] 2024-02-15 17:57
`Creator` is fine by me. I would default for now to the repo name in case of a missing attribute.

**Comment by tkapin** [comment] 2024-02-16 12:10
For the naming of the new attribute, wouldn't `Origin` express the meaning more accurately?

**Comment by mmitche** [comment] 2024-02-16 16:18
> For the naming of the new attribute, wouldn't `Origin` express the meaning more precisely? The repo itself doesn't create anything, it just contains the originating source code of the asset.

Yeah, `Origin` is better

**Comment by tkapin** [comment] 2024-02-20 10:48
Next step: figure out who is going to implement the part that would add the Origin attribute to the MergedManifest.xml.

**Comment by NikolaMilosavljevic** [comment] 2024-02-21 17:09
Would `MergedManifest.xml` be something that is produced in VMR after all repos have produced their individual asset manifests?

Since we don't do publishing yet and we don't have the manifests, this work would need to wait on completion of https://github.com/dotnet/source-build/issues/4101, or even better, be included in that work. I am making good progress on that issue.

**Comment by NikolaMilosavljevic** [comment] 2024-02-21 17:29
It seems that new attribute would be added to `Package` element, and would be something that is done during publishing in each repo. This shouldn't be blocked and can be done independently of my work, but I can certainly do it. Let me know the plan.

**Comment by MichaelSimons** [comment] 2024-02-22 16:00
@andriipatsula has a workaround so this is not blocking at the moment.  Whoever is free first or is blocked by this can pick up the work.

**Comment by andriipatsula** [comment] 2024-02-29 15:37
> Would MergedManifest.xml be something that is produced in VMR after all repos have produced their individual asset manifests?

Yes, we'll have a single MergedManifest.xml file produced for the whole VMR build. @dkurepa is working on this.

I think, we can inject new attribute in asset manifest files (Package & Blob) and forward to the MargedManifest.xml.
* [arcade/PushToAzureDevOpsArtifacts](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs) - creates asset manifest.
* [arcade-services/PushMetadataToBuildAssetRegistry](https://github.com/dotnet/arcade-services/blob/main/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs) - merges asset manifests into singe MergedManifest.xml

But the problem is determining the origin (repo name) during asset manifest creation. As Nikola mentioned, "we don't do publishing yet and we don't have the manifests," so I don't know what the Build.Name would be (I expect to see the name of the VMR repository "dotnet-dotnet" and not the product repo name).

**Comment by andriipatsula** [comment] 2024-03-05 07:56
Yesterday we had a conversation with Nikola and Djuradj. We are waiting for the results of the https://dev.azure.com/dnceng/internal/_build/results?buildId=2393215&view=results build to check how the published artifact manifest looks for the VMR build.

**Comment by andriipatsula** [comment] 2024-03-08 11:58
Asset manifest for the VMR build has `Build.Name` == `dotnet-dotnet` (VMR repo), and this seems reasonable to me. I took @NikolaMilosavljevic 's code changes as a  [baseline](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/pullrequestcreate?sourceRef=dev/nikolam/publishing&targetRef=main&sourceRepositoryId=ddda0dd6-918f-48ba-ba8f-730d9d8c9320&targetRepositoryId=ddda0dd6-918f-48ba-ba8f-730d9d8c9320), on top of which I implemented a PoC [commit](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/a48242f42dd73636bd61a1d9414fd203d8e284ad?refName=refs%2Fheads%2Fdev%2Fapatsula%2Fsource_build_3898) and [tested](https://dev.azure.com/dnceng/internal/_build/results?buildId=2396952&view=results) it. I am going to introduce a new parameter, ManifestOriginRepoName, in the [PushToAzureDevOpsArtifacts](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs) MSBuild task (renamed to PushToBuildStorage) and pass the repository name as a Build command parameter in [/repo-projects/Directory.Build.props](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/a48242f42dd73636bd61a1d9414fd203d8e284ad?path=/repo-projects/Directory.Build.props&version=GBdev/apatsula/source_build_3898&line=89&lineEnd=89&lineStartColumn=1&lineEndColumn=76&type=2&lineStyle=plain&_a=files).

I'll wait until Nikola merges his changes, and I think I need about 1 day to make the PoC production-ready and test it properly. Feel free to check the [commit](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/a48242f42dd73636bd61a1d9414fd203d8e284ad?refName=refs%2Fheads%2Fdev%2Fapatsula%2Fsource_build_3898).

The resulted asset manifest for the emsdk repository looks like:
```xml
<Build PublishingVersion="3" Name="dotnet-dotnet" ...>
<Package Id="Microsoft.NET.Workload.Emscripten.Current.Manifest-9.0.100-preview.2" Version="9.0.0-preview.2.24121.1" Origin="emsdk" />
<Package Id="Microsoft.NET.Workload.Emscripten.Current.Manifest-9.0.100.Transport" Version="9.0.0-preview.2.24121.1" NonShipping="true" Origin="emsdk" />
<Package Id="Microsoft.NET.Workload.Emscripten.net6.Manifest-9.0.100-preview.2" Version="9.0.0-preview.2.24121.1" Origin="emsdk" />
<Package Id="Microsoft.NET.Workload.Emscripten.net7.Manifest-9.0.100-preview.2" Version="9.0.0-preview.2.24121.1" Origin="emsdk" />
<Package Id="Microsoft.NET.Workload.Emscripten.net8.Manifest-9.0.100-preview.2" Version="9.0.0-preview.2.24121.1" Origin="emsdk" />
...
</Build>
```

**Comment by andriipatsula** [comment] 2024-04-16 05:54
First part: https://github.com/dotnet/arcade/pull/14718

**Comment by andriipatsula** [comment] 2024-04-19 09:57
PRs are merged. Example of a VerticalBuild.xml file [here](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQzMzQxMy9hcnRpZmFjdE5hbWUvV2luZG93c194NjRfQXJ0aWZhY3Rz0/content?format=file&subPath=%2FVerticalManifest.xml).

**Closed by andriipatsula** 2024-04-19 09:57 UTC
Labels: area-unified-build
