### ISSUE TITLE
Unclear build steps for building on Windows

### ISSUE THREAD

**Issue by neeraj9** [dotnet/source-build#2378] opened 2021-08-14 17:22 UTC
The build.cmd in the project root folder do not work as-is. I tried for a little bit to build everything from source, but those attempts failed when using Windows operating system. I believe the (just by looking at the script) the Linux build.sh is probably complete and much better than the one available on Windows. (build.cmd).

Let me know what I am missing here, because otherwise it's non-trivial to build everything from source.

```powershell
C:\> dotnet --list-sdks
2.1.817 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.412 [C:\Program Files\dotnet\sdk]
5.0.206 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
```

Build error when running build.ps1 within eng/common folder.

```powershell
PS C:\d\sb> git checkout release/5.0
PS C:\d\sb\eng\common> .\build.ps1
C:\d\sb\Directory.Build.props(9,78): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found. [C:\Users\neerajs\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20426.4\tools\Build.proj]
```

**Comment by omajid** [comment] 2021-08-14 18:43
See https://github.com/dotnet/source-build/issues/1190

**Comment by dseefeld** [comment] 2021-08-19 18:06
Triage: This is a duplicate of #1190

**Closed by dseefeld** 2021-08-19 18:06 UTC
Labels: untriaged
