### ISSUE TITLE
[ArPow Tarball] Review Arcade patches required to build prototype tarball

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#2263] opened 2021-06-18 19:40 UTC
Arcade requires 2 additional patches to build successfully in the tarball prototype.  These patches need to be reviewed and if valid, should be integrated into Arcade.

**Comment by MichaelSimons** [comment] 2021-06-21 16:24
@dseefeld - can you please provide a link to the additional patches you are referring to?

**Comment by MichaelSimons** [comment] 2021-06-21 16:30
Here are the two patches from the ArPow prototype being referenced - https://github.com/dseefeld/linker/tree/tarballCreation/src/SourceBuild/tarball/content/patches/arcade

**Comment by MichaelSimons** [comment] 2021-09-02 18:52
Duplicate of #2345.

**Closed by MichaelSimons** 2021-09-02 18:52 UTC
Labels: area-infra
