### ISSUE TITLE
Remove workaround that inserts Microsoft.Build.CentralPackageVersions as source-built SDK override

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#933] opened 2018-12-14 16:33 UTC
I'm filing this issue to link from a code comment describing this workaround. https://github.com/dotnet/source-build/pull/930#issuecomment-447041144

> Now we get a "this should never happen" (per NuGet source code) error on two legs of CI--one online tarball build and one offline tarball build. Seems like flakiness, maybe race condition? It doesn't repro for me locally. I don't see any way to drill into what actually failed to happen (especially without a local repro). Message:
> 
> ```
> [SourceBuiltSdkResolver] Looking for SDK Microsoft.Build.CentralPackageVersions. Detected config(s) in env: 'REPO_TOOLSET' for 'RoslynTools.RepoToolset/1.0.0-source-built' at '/tb/tarball_57394/Tools/source-built/RoslynTools.RepoToolset/sdk/'
> /tb/tarball_57394/src/msbuild/Directory.Build.targets(14,3): error : [SourceBuiltSdkResolver] 0 overrides found for 'Microsoft.Build.CentralPackageVersions'
> /tb/tarball_57394/src/msbuild/Directory.Build.targets(14,3): error : Failed to resolve SDK 'Microsoft.Build.CentralPackageVersions'. Package restore was successful but a package with the ID of "Microsoft.Build.CentralPackageVersions" was not installed.
> /tb/tarball_57394/src/msbuild/Directory.Build.targets(14,33): error MSB4236: The SDK 'Microsoft.Build.CentralPackageVersions' specified could not be found. [/tb/tarball_57394/src/msbuild/src/Build/Microsoft.Build.csproj]
> ```
> (The `SourceBuiltSdkResolver` not finding any overrides is normal, it's just that MSBuild only shows the message when all resolvers fail to acquire the requested SDK.)
> 
> [Source of the NuGet error message:](https://github.com/NuGet/NuGet.Client/blob/7e85ef267561d0aee4831fc2ab1d2456c5c1985c/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/NuGetSdkResolver.cs#L164-L166)
> 
> ```
> // This should never happen because we were told the restore succeeded.
> // If we can't find the package from GetAllInstalled(), we probably did something wrong with the NuGet API
> errors.Add(string.Format(CultureInfo.CurrentCulture, Strings.PackageWasNotInstalled, sdk, sdk.Name));
> ```
> `Strings.PackageWasNotInstalled` is `Failed to resolve SDK '{0}'. Package restore was successful but a package with the ID of "{1}" was not installed.`
> 
> I'm going to work around this by using `SourceBuiltSdkResolver` to find `Microsoft.Build.CentralPackageVersions`, bypassing the NuGet resolver entirely. It's a ref-only prebuilt so we should have easy access to it.

**Comment by dagood** [comment] 2018-12-14 19:50
@nkolev92, any ideas how to get more info on what's happening with this nuget SDK resolver error?

We unzip and repack the SDK package that's failing to install, so we might be invalidating a signature or something like that. The nuget.config at the time might be interesting--all local sources, and the nupkg is in `/work/reference-packages/packages/`:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="source-built" value="/work/bin/obj/x64/Release/blob-feed/packages/" />
    <add key="reference-packages" value="/work/reference-packages/packages/" />
    <add key="previously-source-built" value="/work/prebuilt/source-built/" />
    <add key="prebuilt" value="/work/prebuilt/nuget-packages/" />
  </packageSources>
</configuration>
```

If you have any ideas for things that need to be examined on the build machine, I can try reverting the workaround in a branch, adding some manual stuff to export the relevant files, and running the build until it repros. (I don't know how often this is.)

**Comment by nkolev92** [comment] 2018-12-14 20:00
Is it possible that https://github.com/NuGet/Home/issues/7599 is the root cause of the issue? 

The code lives in the NuGet repo, but is actually owned by MSBuild, so they'd be best suited to investigated. 

//cc @livarcocc @jeffkl @jainaashish

**Comment by dagood** [comment] 2018-12-14 20:55
Seems unlikely to me after trying a few more things:
* Intentionally mess with the package contents to fail verification.
   * This doesn't cause a repro.
* Check if repacked packages pass signing verification in the first place.
  * They don't seem to ever verify, even when the issue doesn't repro. The validation error is: `NU3005: The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).`

`dotnet --info`, by the way:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6
```

I think it might be possible for me to build a replacement `NuGetSdkResolver` that does more logging and swap it in, to figure this out. I'm giving it a shot.

**Comment by dagood** [comment] 2018-12-17 17:02
I'm not sure what to do to replace it, based on the signatures. It doesn't look like a drop-in, but I'm not familiar with all these NuGet types:

```C#
    public static async Task<IReadOnlyList<RestoreSummary>> RunAsync(RestoreArgs restoreContext, CancellationToken token);
    public static async Task<IReadOnlyList<RestoreSummary>> RunAsync(RestoreArgs restoreContext);
    public static async Task<IReadOnlyList<RestoreResultPair>> RunWithoutCommit(IEnumerable<RestoreSummaryRequest> restoreRequests, RestoreArgs restoreContext);
    public static async Task<IReadOnlyList<RestoreSummaryRequest>> GetRequests(RestoreArgs restoreContext);
    public static async Task<RestoreSummary> CommitAsync(RestoreResultPair restoreResult, CancellationToken token);
```

What I did is add some more errors with more details:

```C#
// This should never happen because we were told the restore succeeded.
// If we can't find the package from GetAllInstalled(), we probably did something wrong with the NuGet API
errors.Add(string.Format(CultureInfo.CurrentCulture, "Strings.PackageWasNotInstalled", sdk, sdk.Name));

errors.Add($"Success: {result.Success}");

errors.Add(
    "All installed:\n" +
    string.Join("\n", result.GetAllInstalled()));

errors.Add(
    "All unresolved:\n" +
    string.Join("\n", result.GetAllUnresolved()));

errors.Add($"Result as JSON: {JObject.FromObject(result).ToString(Formatting.Indented)}");
```

But with repeated builds with that added in, I haven't been able to get the original issue to repro. 😞 This is my implementation, FWIW: https://github.com/dotnet/source-build/compare/4aff195b41...dagood:repro-sdk-diag-all-1

---

A few ways forward:

1. Keep the workaround (using the source-built SDK resolver) that ensures this won't repro.
2. Remove the workaround because it doesn't seem to repro. However, if it does repro, we're in no better position to find out what happened. The problem becomes a source of flakiness.
   * I'm relatively OK with this, we can add the workaround from 1 back in if it repros again.
3. Add the "debug version" of the NuGet resolver to `master`, so that if we get a repro in some PR in the future, we'll have more info. However, this needs to be kept in sync with the version the SDK toolset uses--extra maintenance.

It seems like it would be ideal if the built-in NuGet resolver could get an env var flag to enable restore commit assets and for that to be uptaken in an SDK, then we would use that SDK and set the flag. That would take a long time, though.

I'm going to submit a PR for 2 for now. I think 3 is fine if there's a strong desire on the MSBuild side to figure out what's going on.

**Comment by dagood** [comment] 2018-12-18 00:17
The PR I submitted to remove the workaround actually hit the error during its CI, so I'm leaving the workaround in.

@rainersigwald, @livarcocc, do you have any particular desire to track down this flakiness or any tips?

**Comment by crummel** [comment] 2019-07-11 21:24
We intend to continue using CentralPackageVersions as an SDK override anyway - closing this issue since it's really for debugging a NuGet issue.

**Closed by crummel** 2019-07-11 21:24 UTC
Labels: triaged
