### ISSUE TITLE
spectre.console repo fails to build in SBE

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3817] opened 2024-01-02 22:36 UTC
The changes from https://github.com/dotnet/source-build-externals/pull/244 are causing the following error in internal CI:

```
  /__w/1/s/artifacts/sb/src/repo-projects/spectre-console.proj(21,7): error MSB3073: The command "/__w/1/s/.dotnet/dotnet restore /bl:restore.binlog /__w/1/s/artifacts/sb/src/src/spectre-console//src/Spectre.Console/Spectre.Console.csproj /p:Configuration=Release /v:minimal >> /__w/1/s/artifacts/sb/src/artifacts/bin/spectre-console/logs/spectre-console.log 2>&1 /p:Version=0.48.0 /p:TargetFrameworks=net9.0" exited with code 145.
##[error]artifacts/sb/src/repo-projects/spectre-console.proj(21,7): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "/__w/1/s/.dotnet/dotnet restore /bl:restore.binlog /__w/1/s/artifacts/sb/src/src/spectre-console//src/Spectre.Console/Spectre.Console.csproj /p:Configuration=Release /v:minimal >> /__w/1/s/artifacts/sb/src/artifacts/bin/spectre-console/logs/spectre-console.log 2>&1 /p:Version=0.48.0 /p:TargetFrameworks=net9.0" exited with code 145.
    The command could not be loaded, possibly because:
      * You intended to execute a .NET application:
          The application 'restore' does not exist.
      * You intended to execute a .NET SDK command:
          A compatible .NET SDK was not found.
    
    Requested SDK version: 8.0.100
    global.json file: /__w/1/s/artifacts/sb/src/src/spectre-console/global.json
    
    Installed SDKs:
    
    Install the [8.0.100] .NET SDK or update [/__w/1/s/artifacts/sb/src/src/spectre-console/global.json] to match an installed SDK.
    
    Learn about SDK resolution:
    https://aka.ms/dotnet/sdk-not-found
    9.0.100-alpha.1.23615.4 [/__w/1/s/.dotnet/sdk]
    
    'spectre-console' failed during build.
```

[Build link (internal)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=512682&view=logs&j=d21bfc57-2f78-5de1-fdb5-cfedcec99163&t=0e9fb5e6-5575-5ee9-3738-8ed741f427c3)

cc @baronfel

**Comment by baronfel** [comment] 2024-01-02 22:38
I suppose we could remove the global.json, or add RollForward for Major and allowPrereleases. Either of those would be a patch. Is that how we'd typically solve this kind of problem?

**Comment by MichaelSimons** [comment] 2024-01-02 23:47
I don't think this is an issue with the global.json.  The problem that occurred here is that over the time from when your PR was created to when it was merged, Arcade was upgraded which brought in the changes that updated NetCurrent from net8.0 to net9.0.  A patch is likely going to be needed to add net9.0 to Spectre.Console.csproj's TargetFrameworks until which time the change can be pushed upstream.

Long term I don't think this code is working as intended here - https://github.com/dotnet/source-build-externals/blob/main/repo-projects/spectre-console.proj#L18.  The reason being is the project does not honor the passed in TargetFrameworks.  Ideally the project would be modified to use the same pattern as DockerCredsProvider - https://github.com/mthalman/docker-creds-provider/blob/b381eafbeecb1039f5839fc98ef45e7b3e52dee9/src/Valleysoft.DockerCredsProvider/Valleysoft.DockerCredsProvider.csproj#L4

**Comment by baronfel** [comment] 2024-01-03 15:41
Oh, thank you! Separately I'm confused by this behavior because my understanding of MSBuild semantics was that a property provided on the CLI (`-p TargetFrameworks=net9.0`) became a global property for all projects built by the command, meaning that any project-file-level modifications to that Property could not apply.

**Comment by mthalman** [comment] 2024-01-03 16:21
Looking at this closer, I do think the global.json is the issue, not the TFM. The global.json is saying I want 8.0.100 to be used. But that's not installed on the machine. What the `TargetFrameworks` value is doesn't really matter since the 9.0 SDK is capable of building them as is.

**Comment by MichaelSimons** [comment] 2024-01-03 16:30
> Looking at this closer, I do think the global.json is the issue, not the TFM. The global.json is saying I want 8.0.100 to be used. But that's not installed on the machine. What the `TargetFrameworks` value is doesn't really matter since the 9.0 SDK is capable of building them as is.

Isn't this Target intended to update the global.json?  https://github.com/dotnet/dotnet/blob/main/src/source-build-externals/repo-projects/Directory.Build.targets#L114

**Comment by MichaelSimons** [comment] 2024-01-03 16:34
Perhaps the GlobalJsonFile property needs to simply be set in the spectre repo project?

**Comment by mthalman** [comment] 2024-01-03 19:34
> Perhaps the GlobalJsonFile property needs to simply be set in the spectre repo project?

Yeah, I will try that. Unfortunately, it uses the `UpdateJson` task which has long been removed from this repo. This repo has no custom MSBuild tasks defined at all. So I'll have to add back that infra.

**Closed** 2024-01-04 20:50 UTC
Labels: area-upstream-fix
