### ISSUE TITLE
Consider setting CheckEolTargetFramework=false globally

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#3081] opened 2022-10-21 17:25 UTC
These warnings almost always hit source-build a release cycle before they hit the contributing repos due to our N->N rebuild testing.  While upgrading TFMs is something we want, we can detect issues with non-current TFMs using prebuilt detection, so removing this warning (which is usually made an error) shouldn't make source-build more dangerous.

**Comment by MichaelSimons** [comment] 2022-10-27 16:09
[Triage] In the VMR 9 timeframe we should consider removing this global setting so that the product usages of the EOL TFMs are forced to be fixed.  However in the meantime when source-build is not the official build, this is a source of breaks that require last minute patches with no value so disabling it globally seems like the right decision.

**Comment by ViktorHofer** [comment] 2023-12-05 11:50
The switch is still set globally for all VMR projects: https://github.com/dotnet/installer/blob/c01b62c0fcfdfd7af0c1af9a476faa8756bf913d/src/SourceBuild/content/repo-projects/Directory.Build.props#L123-L124

**Comment by ViktorHofer** [comment] 2023-12-05 12:02
OK reading further into https://github.com/dotnet/installer/pull/15222, it looks like the TFM validation was globally suppressed for all repositories. I really want to warn on doing this.

With that switch globally suppressed, components silently compile against `netstandard2.0` assets instead of `NetCurrent` when building from source. Allowing that "TFM downgrade" could result in unexpected behavior. We in runtime don't even run tests against the netstandard2.0 TFM. It most certainly results in a significant performance degradation.

**Comment by MichaelSimons** [comment] 2023-12-05 14:47
> With that switch globally suppressed, components silently compile against netstandard2.0 assets instead of NetCurrent when building from source.

I'm not understanding this statement.  Does your statement only apply to components that target an EOL framework?

This was originally implemented before the introduction of NetCurrent.  This was a frustrating situation for source-build and was not something source-build specific - the Microsoft builds were targeting EOL TFMs as well.  Regardless, with the introduction of NetCurrent, this won't be an issue anymore (at least it would be an edge case if it did). so removing this global setting is good.

**Comment by ViktorHofer** [comment] 2023-12-05 17:04
> I'm not understanding this statement. Is that a general statement or apply to components that target an EOL framework?

Let me clarify. For source build this affects any component that doesn't target `NetCurrent`. For non source build this means EOL frameworks (i.e. net5.0.).

**Comment by MichaelSimons** [comment] 2023-12-07 17:35
[Triage] - Agreed we should remove this global setting.  Fix should target the 8.0 branch.

**Comment by ellahathaway** [comment] 2024-01-02 16:40
Closing since https://github.com/dotnet/installer/pull/17964 was merged.

**Closed by ellahathaway** 2024-01-02 16:40 UTC
Labels: area-infra, up-for-grabs
