### ISSUE TITLE
[source-build-release] Pipeline should allow and properly consume custom release branch names

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3652] opened 2023-10-11 19:40 UTC
During October release I've encountered 2 issues that were likely introduced by usage of custom release branch name:

- AzDO validation builds for 6.0 and 7.0 were created to target regular branch, ignoring my input for `Release branch name` parameter.
- `Submit Release PR` step failed

Example pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2282626&view=results

**Comment by NikolaMilosavljevic** [comment] 2023-10-27 17:18
Additionally, this should cover the mirroring step as well. Both `security-partners-dotnet` and `dotnet-security-partners` would need to have custom branches created, for mirroring to be successful. We should ensure that branch in `security-partners-dotnet` is created off of latest from previous month's release, which could have also used a custom branch - i.e. we shouldn't use regular servicing branch as baseline.

**Comment by oleksandr-didyk** [comment] 2023-11-07 13:28
Hey @NikolaMilosavljevic, from reading the issues it seems there are several different suggestions / problems here, so I'll try to split them based on my understanding, Would appreciate if you could verify if I'm right:

1. Mirroring, specifically creating the PR with the tarball, is selecting the target branch based on some pre-defined logic rather then using the `releaseBranchName` parameter. The parameter mentioned should also dictate the target branch in `dotnet-security-partners`
2. Pipeline uses the servicing branch as the base when creating the branch for mirroring. It should instead use the branch containing the previous month's release. Question here: doesn't servicing branch always contain the latest servicing release? Or am I miss-understanding this point
3. `Submit Release PR` stage tried finding a branch in installer corresponding to the one in `releaseBranchName` parameter but failed. The logic for finding the installer branch should be improved

Please lemme know if the assessment above is correct and if point 2 makes sense. Thanks!

**Comment by oleksandr-didyk** [comment] 2023-11-13 13:44
@mthalman pinging you here since you might have more context into the questions / topics described above. Thanks in advance!

**Comment by oleksandr-didyk** [comment] 2023-11-13 16:39
> The branch that gets created in dotnet-security-partners/dotnet is not even necessary. The branches there aren't even maintained. It's the tags that matter. So we should stop causing the creation of a branch to dotnet-security-partners/dotnet when a custom branch name is provided.

Maybe then we should stop doing it in all cases?
Since instead of differentiating between custom / non-custom branch names we could just always treat the branch as custom and assume less about the other branches we need to use

**Comment by mthalman** [comment] 2023-11-13 16:44
Yes, I was referring to custom branch names specifically because the normal branches already exist and aren't being created with these servicing releases. But yes, it applies to all branches.

**Comment by oleksandr-didyk** [comment] 2023-11-15 10:37
Synced with Matt, went through the way mirroring is currently done and what is the end result we expect. To outline the issue and its solution again:

### `security-partners-dotnet`

The pipeline uses a throw-away branch (example: `dev/6.0.125-nov2023`) to extract tarball contents into and open a PR against a dedicated release branch for that specific major .NET version (example: `release/6.0.1xx`). This PR is then manually merged as part of the release.

This is the correct, expected behaviour. The main goals of this is to have the release branch HEAD point to the current state for that specific .NET version (i.e. latest servicing) as well as have a concrete history of updates on the branch:
![image](https://github.com/dotnet/source-build/assets/106967057/fbb88217-bf10-4857-a99e-bc36c2c1aece)

### `dotnet-security-partners/dotnet` for pre-VMR only

The pipeline strips the `internal/` part of the `releaseBranchName` and assumes the result is the branch with the latest tarball in `security-partners-dotnet`.  It then tags the HEAD of this branch and pushes the tag to `dotnet-security-partners/dotnet`.

This is only correct if the `releaseBranchName` is non-custom, as in confronts to the `internal/release/<major-version>.0.1xx` pattern. In other cases the logic will fail as the branch it is trying to tag does not exist, at least not without manual intervention.

The logic should reference the release branch for the given major version as it will always point to the latest state of the serviced version.

### `installer` release PR

Same as with `dotnet-security-partners/dotnet`, the pipeline strips the `internal/` part of the `releaseBranchName` and assumes the result is the branch it needs to open the release PR against. This of course would fail for a custom `releaseBranchName` parameter and the pipeline should instead always open the release PR against the established release branch for the given major version.

The solution for most issues found is to simply re-wire the pipeline to use the major version instead of the `releaseBranchName` to figure out the branches in needs to interact with in different repositories.

The major version could be extracted from the tag (as it is already done). It can also be done once in the pre-release stage and simply exposed to the other stages as a step output

**Comment by oleksandr-didyk** [comment] 2023-11-21 12:24
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35404

**Comment by oleksandr-didyk** [comment] 2023-11-28 12:17
PR merged, closing as `Done`

**Closed by oleksandr-didyk** 2023-11-28 12:17 UTC
Labels: area-release
