### ISSUE TITLE
CentOSStream8_Online_PreviousSourceBuiltSDK failing during runtime build

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3905] opened 2024-01-08 16:48 UTC
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2347529&view=logs&j=273502c4-a2ec-5aef-1ae2-d1442236a3bf&t=77157322-8c53-5d9f-77f5-d2b1faa7e281&l=6947

```
EXEC : error message: An attempt was made to load a program with an incorrect format. [/vmr/src/runtime/artifacts/sb/src/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj]
       (0x8007000B)
      Failed to create CoreCLR, HRESULT: 0x8007000B
    /vmr/src/runtime/artifacts/sb/src/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj(60,5): error MSB3073: The command "/vmr/src/runtime/artifacts/sb/src/artifacts/bin/crossgen2_publish/x64/Release/centos.8-x64/publish/crossgen2 /vmr/src/runtime/artifacts/sb/src/artifacts/bin/coreclr/linux.x64.Release/IL/System.Private.CoreLib.dll --out /vmr/src/runtime/artifacts/sb/src/artifacts/obj/Microsoft.NETCore.App.Crossgen2/Release/net9.0/centos.8-x64/S.P.C.tmp" exited with code 137.
```

**Comment by mthalman** [comment] 2024-01-08 18:41
Duplicate of https://github.com/dotnet/source-build/issues/3815

**Closed by mthalman** 2024-01-08 18:41 UTC
Labels: area-upstream-fix, untriaged, ops-monitor
