### ISSUE TITLE
More info on VMR onboarding is needed in "new repo" doc

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3703] opened 2023-11-01 15:02 UTC
The ["new repo" doc](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-repo.md) needs more info on incorporating the new repo into the VMR:
* Adding a new <repo>.proj file to [repo-projects](https://github.com/dotnet/installer/tree/main/src/SourceBuild/content/repo-projects).
* Referencing the new repo from [dotnet.proj](https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/repo-projects/dotnet.proj), in dependency order.
* Adding a new [license baseline file](https://github.com/dotnet/installer/tree/main/src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/baselines/licenses) for the repo with default content:
  ```json
  {
    "files": []
  }<no new line>
  ```

**Comment by MichaelSimons** [comment] 2024-07-11 16:47
This is a duplicate of https://github.com/dotnet/source-build/issues/3600.

**Closed by MichaelSimons** 2024-07-11 16:47 UTC
Labels: area-doc
