### ISSUE TITLE
[main] Runtime build fails due to ApiCompat errors

### ISSUE THREAD

**Issue by lbussell** [dotnet/source-build#3025] opened 2022-09-14 21:10 UTC
```
/tarball/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/7.0.100-rc.1.22404.18/build/Microsoft.NET.ApiCompat.ValidatePackage.targets(32,5): error CP0002: Member 'Microsoft.Extensions.Caching.Memory.PostEvictionDelegate.PostEvictionDelegate(object, System.IntPtr)' exists on lib/net6.0/Microsoft.Extensions.Caching.Abstractions.dll but not on lib/net7.0/Microsoft.Extensions.Caching.Abstractions.dll [/tarball/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj]
    
    Build FAILED.
    
    /tarball/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/7.0.100-rc.1.22404.18/build/Microsoft.NET.ApiCompat.ValidatePackage.targets(32,5): error CP0002: Member 'Microsoft.Extensions.Caching.Memory.PostEvictionDelegate.PostEvictionDelegate(object, System.IntPtr)' exists on lib/net6.0/Microsoft.Extensions.Caching.Abstractions.dll but not on lib/net7.0/Microsoft.Extensions.Caching.Abstractions.dll [/tarball/src/runtime/artifacts/source-build/self/src/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj]
        0 Warning(s)
        1 Error(s)
```

This has happened before when a repo has Api Compatibility suppressions between two specific TFMs, and source-build changes some of the TFMs. This causes ApiCompat to compare the wrong outputs and as a result it doesn't pick up the right suppressions. In SDK for net7.0 we fixed this by disabling ApiCompat when we change around the TargetFrameworks. Otherwise, we would need different compatibility suppressions for source-build and non-source-build.

**Comment by lbussell** [comment] 2022-09-14 21:23
This issue was introduced with https://github.com/dotnet/installer/pull/14402.

**Comment by MichaelSimons** [comment] 2022-10-13 19:11
Closing as a duplicate of https://github.com/dotnet/source-build/issues/3067.

**Closed by MichaelSimons** 2022-10-13 19:11 UTC
Labels: area-upstream-fix
