### ISSUE TITLE
Update CI bootstrap test to take advantage of BYO-packages

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#1450] opened 2020-01-16 21:16 UTC
This has the ability to cut down on the time it takes to build and will also exercise the code to allow users to bring their own previously-built and reference packages.

Depends on https://github.com/dotnet/source-build/pull/1434.

cc @dseefeld

**Comment by dagood** [comment] 2020-02-13 19:49
Duplicate of #1476

**Closed by dagood** 2020-02-13 19:49 UTC
