### ISSUE TITLE
Missing xml docs for some dlls

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1686] opened 2020-07-23 18:38 UTC
I am looking through my .NET Core build and trying to make sure that we have xml documentation for targeting packs. I see a number of `.dll` files have no corresponding `.xml` files. I am not sure if I am doing something wrong or if the documentation is actually missing:

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.106
 Commit:    0f94483edc

Runtime Environment:
 OS Name:     fedora
 OS Version:  32
 OS Platform: Linux
 RID:         fedora.32-x64
 Base Path:   /usr/lib64/dotnet/sdk/3.1.106/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.106 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

$ find /usr/lib64/dotnet -iname 'System.IO.Pipelines*'
/usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.IO.Pipelines.dll
/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App/3.1.6/System.IO.Pipelines.dl
```

There is no `.xml` file for `System.IO.Pipelines.dll`. Is that expected?

I looked at the Microsoft tarball, and it has the same issue:

```
$ find -iname 'System.IO.Pipelines.*'
./packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.IO.Pipelines.dll
./shared/Microsoft.AspNetCore.App/3.1.6/System.IO.Pipelines.dll
```

Here's my test script:

```bash
#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

dotnet_dir=$(dirname "$(readlink -f "$(command -v dotnet)")")
echo "$dotnet_dir"

targeting_packs_dir="$dotnet_dir/packs/"
echo "$targeting_packs_dir"

error=0
while IFS= read -r -d '' dll_file; do
    xml_doc_file=${dll_file%.*}.xml
    # echo "$xml_doc_file"
    if [ ! -f "$xml_doc_file" ]; then
        error=1
        echo "error: missing $xml_doc_file"
    fi
done < <(find "$targeting_packs_dir" -name '*.dll' -print0)

exit $error
```

<details><summary>This is the complete output</summary>

```
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Dynamic.Runtime.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Memory.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Tasks.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Console.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Numerics.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.UnmanagedMemoryStream.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Globalization.Extensions.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.Debug.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.XPath.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.ReaderWriter.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.FileSystem.DriveInfo.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Timer.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/Microsoft.Win32.Primitives.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.Compression.FileSystem.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ServiceModel.Web.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Collections.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.Linq.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.DispatchProxy.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ComponentModel.Composition.xml                                                                                                              
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Drawing.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ComponentModel.EventBasedAsync.xml                                                                                                          
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.MemoryMappedFiles.xml                                                                                                                    
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Serialization.Formatters.xml                                                                                                        
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Http.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.Compression.ZipFile.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.ThreadPool.xml                                                                                                                    
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.InteropServices.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.StackTrace.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Overlapped.xml                                                                                                                    
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Text.Encoding.Extensions.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Claims.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.XDocument.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Linq.Parallel.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Collections.Concurrent.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.FileSystem.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Cryptography.Csp.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.Pipes.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.FileSystem.Primitives.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Serialization.Primitives.xml                                                                                                        
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Principal.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Cryptography.Algorithms.xml                                                                                                        
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.Serialization.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Data.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.WebHeaderCollection.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Globalization.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Collections.NonGeneric.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.Process.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Resources.ResourceManager.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Serialization.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Serialization.Xml.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Ping.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.Compression.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Resources.Writer.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Cryptography.X509Certificates.xml                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ObjectModel.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Cryptography.Primitives.xml                                                                                                        
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.NetworkInformation.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Resources.Reader.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.Emit.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Tasks.Parallel.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Data.Common.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.CompilerServices.VisualC.xml                                                                                                        
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.Primitives.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ValueTuple.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.NameResolution.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.AppContext.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.Cryptography.Encoding.xml                                                                                                          
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Extensions.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.FileSystem.Watcher.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/mscorlib.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Security.SecureString.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Text.Encoding.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.IO.IsolatedStorage.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.Tools.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.FileVersionInfo.xml                                                                                                             
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Tasks.Extensions.xml                                                                                                              
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Globalization.Calendars.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.Emit.ILGeneration.xml                                                                                                            
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Numerics.Vectors.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.TextWriterTraceListener.xml                                                                                                     
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Primitives.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Web.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ComponentModel.TypeConverter.xml                                                                                                            
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ComponentModel.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Requests.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.XmlDocument.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Sockets.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.Contracts.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.ComponentModel.Primitives.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Core.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Threading.Thread.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Linq.Expressions.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Handles.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.XmlSerializer.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.Security.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Transactions.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.InteropServices.RuntimeInformation.xml                                                                                              
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Buffers.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Linq.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Text.RegularExpressions.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.WebSockets.Client.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.Tracing.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Collections.Specialized.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Numerics.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Diagnostics.TraceSource.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Net.WebSockets.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.Emit.Lightweight.xml                                                                                                             
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Reflection.Extensions.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Linq.Queryable.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Drawing.Primitives.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Runtime.Serialization.Json.xml                                                                                                              
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Xml.XPath.XDocument.xml
error: missing /usr/lib64/dotnet/packs/NETStandard.Library.Ref/2.1.0/ref/netstandard2.1/System.Windows.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Security.Permissions.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Security.Principal.Windows.xml                                                                                                          
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/Microsoft.Win32.Registry.xml                                                                                                                   
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Windows.Extensions.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Diagnostics.EventLog.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.IO.Pipelines.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Security.AccessControl.xml                                                                                                              
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Security.Cryptography.Cng.xml                                                                                                           
error: missing /usr/lib64/dotnet/packs/Microsoft.AspNetCore.App.Ref/3.1.3/ref/netcoreapp3.1/System.Security.Cryptography.Xml.xml                                                                                                           
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Dynamic.Runtime.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Numerics.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.IO.UnmanagedMemoryStream.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Globalization.Extensions.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.IO.Compression.FileSystem.xml                                                                                                              
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.ServiceModel.Web.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Xml.Linq.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Drawing.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/netstandard.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Reflection.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.IO.FileSystem.Primitives.xml                                                                                                               
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Xml.Serialization.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Data.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Globalization.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.Serialization.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Resources.Reader.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Configuration.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.IO.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.ValueTuple.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.ComponentModel.DataAnnotations.xml                                                                                                         
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.AppContext.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.ServiceProcess.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/mscorlib.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Security.SecureString.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Text.Encoding.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/Microsoft.VisualBasic.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Threading.Tasks.Extensions.xml                                                                                                             
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Globalization.Calendars.xml                                                                                                                
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Web.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Data.DataSetExtensions.xml                                                                                                                 
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Xml.XmlDocument.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Core.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Security.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Runtime.Handles.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Transactions.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Net.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Reflection.Extensions.xml                                                                                                                  
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Xml.xml
error: missing /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/3.1.0/ref/netcoreapp3.1/System.Windows.xml

```
</details>

**Comment by dagood** [comment] 2020-07-23 19:43
Hmm. This library is created by CoreFX as a platform extension not in the netcoreapp shared framework, then ASP.NET Core is bringing it into its own shared framework. I believe the DLL is present in the ASP.NET Core targeting pack because users need/want to compile against the version of the library in the shared framework.

Based on that, I would expect the XML files to be included in the targeting pack... this lets people using these refs get at the docs without setting up a redundant System.IO.Pipelines package reference. (Although I don't actually know if setting that up would get the docs working end-to-end. I'm not really familiar with how they get picked up, but I think they have to be adjacent to the DLL that'll be used to compile, and maybe the targeting pack one would take precedence and prevent discovery.)

https://www.nuget.org/packages/System.IO.Pipelines/4.7.2 looks like it has the XML, I would guess the redist logic just isn't set up to include it.

I think this is an issue in https://github.com/dotnet/aspnetcore, and if it's fixed there, we'll semi-automatically get a fix in source-build when we generate the new targeting pack in source-build-reference-packages. (Whether it's fixed in 5.0, 3.1, or both.)

Do you mind reporting this as a bug there? The most direct assets to examine and point at are probably these because there's no potential for error in the SDK packing infra:
https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/3.1.0
https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/3.1.3
https://www.nuget.org/packages/System.IO.Pipelines/4.7.2

**Comment by omajid** [comment] 2020-09-18 13:35
Sorry, I dropped the ball on this issue.

Revisiting the issue now, I see things are missing even in Microsoft.NETCore.App:

```
# Microsoft SDK 5.0 Preview 8:
$ tar tf dotnet-microsoft-built-sdk-5.0.100-preview.8.20417.9.tar.gz | grep 'System.IO.*xml'
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.MemoryMappedFiles.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.Compression.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.Compression.ZipFile.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.FileSystem.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.FileSystem.Watcher.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.FileSystem.DriveInfo.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.Compression.Brotli.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.Pipes.xml
./packs/Microsoft.NETCore.App.Ref/5.0.0-preview.8.20407.11/ref/net5.0/System.IO.IsolatedStorage.xml

# Source build 5.0 Preview 8
$ ls /usr/lib64/dotnet/packs/Microsoft.NETCore.App.Ref/
5.0.0-preview.8.20407.11
$ find /usr/lib64/dotnet -iname 'System.*xml'
$ find /usr/lib64/dotnet -iname 'System*xml'
```

What reproduce produces this? dotnet/sdk?

**Comment by dagood** [comment] 2020-09-18 14:46
> Revisiting the issue now [5.0 p8], I see things are missing even in Microsoft.NETCore.App:

This is most likely just a symptom of the targeting pack being built in the repo rather than dotnet/source-build-reference-packages. A regression of https://github.com/dotnet/source-build/issues/1578. I don't think we've run the release checklist on a 5.0 build yet, which has a step to catch this.

The original issue is about some XML files that don't show up in the Microsoft **or** source-build targeting pack, which is a separate issue that I think should be reported to https://github.com/dotnet/aspnetcore.

/cc @crummel @dseefeld

**Comment by dagood** [comment] 2020-09-18 19:55
Ah, the source-build side of the 5.0 issue is actually tracked at https://github.com/dotnet/source-build/issues/1703.

Thanks for filing https://github.com/dotnet/runtime/issues/42459 for the dotnet/runtime side of the 5.0 issue.

There's still a potential bug with 3.1: https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/3.1.8 still doesn't have a `System.IO.Pipelines.xml`. I've filed https://github.com/dotnet/aspnetcore/issues/26068 to track the upstream fix.

I don't think there's anything extra that this issue is tracking at this point--closing.

**Closed by dagood** 2020-09-18 19:55 UTC
Labels: area-build, area-upstream-fix, triaged

**Comment by omajid** [comment] 2020-09-18 20:30
Thanks for filing dotnet/aspnetcore#26068. I didn't realize that things need to be fixed in multiple places.
