### ISSUE TITLE
.NET 9: Enable full Windows source-build

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3036] opened 2022-09-21 17:54 UTC
### Describe the Problem

Tracking issue to cover .NET 9 official enablement of Windows source-build

**Comment by MichaelSimons** [comment] 2022-09-22 18:17
[Triage] Closing as a duplicate of https://github.com/dotnet/source-build/issues/2910.

**Closed by MichaelSimons** 2022-09-22 18:17 UTC
Labels: area-product-experience, untriaged
