### ISSUE TITLE
Release pipeline: Uploaded PSB artifacts for 8.0 Preview release uses wrong file name

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3383] opened 2023-04-12 21:15 UTC
As part of the .NET 8 Preview 3 release, the pipeline uploads the PSB artifact tarball to blob storage. It uploaded with this filename: `Private.SourceBuilt.Artifacts.8.0.100.centos.8-x64.tar.gz`. That's incorrect because it should be including the preview number and build number. That filename would actually conflict with the tarball of the 8.0 GA release. This is the correct name it should have used: `Private.SourceBuilt.Artifacts.8.0.100-preview.3.23178.7.centos.8-x64.tar.gz`.

**Comment by mthalman** [comment] 2023-04-12 21:17
Is this a duplicate of https://github.com/dotnet/source-build/issues/3268? Not sure if the release pipeline is causing this or not.

**Comment by MichaelSimons** [comment] 2023-04-12 23:43
I think this is a duplicate of #3268.

**Closed** 2023-04-13 16:12 UTC
Labels: area-release, untriaged
