### ISSUE TITLE
Are .NET SDK and Runtime fully reproducible (yet)?

### ISSUE THREAD

**Issue by geekley** [dotnet/source-build#2648] opened 2021-11-30 03:18 UTC
If I understand [this post](https://devblogs.microsoft.com/dotnet/announcing-net-6/#source-build) correctly, it seems .NET devs intend or are trying to make .NET (SDK and/or Runtime?) fully reproducible:
> As a side note, source build is a big step towards reproducible builds, which we also strongly believe in. The .NET SDK and C# compiler have significant reproducible build capabilities.

So my questions:
- Are both .NET 6 SDK and Runtime (the binaries from Microsoft) fully reproducible yet? If not, will they be in the future?
- What about previous versions of .NET?
- What is the best way I can be notified when .NET is fully reproducible?
- Will there be packages in official Linux apt repositories such as Debian and Ubuntu when that happens?
- Is there any intention to get .NET listed [here](https://reproducible-builds.org/projects/) when that happens?

**Comment by eerhardt** [comment] 2021-12-03 16:41
cc @MichaelSimons @dseefeld @dleeapho

**Comment by mmitche** [comment] 2021-12-03 22:49
Hey @geekley This is a complex question :)

The binaries produced by Microsoft (what shows up on the https://dot.net download site) are not what I would consider reproducible at this point, and we have quite long way to go to that point. The full Microsoft runtime and SDK builds rely on quite a lot of very complex orchestration produce their artifacts.

The source-build version of .NET is **much** closer to a reproducible build (since you can at least package the whole thing up and build it on a single machine), but the source-build methodology is not how the https://dot.net or NuGet.org bits are produced. This is partly historical (source-build is a newer effort), and partly because there is a decent number of "joins" in the build. That is, places where we need intermediates that must be produced natively on various OS's to be combined into a single package or asset. Source-build produces a single vertical, which is fantastically simpler and more amenable to reproducible builds.

Long term, reproducible builds will probably happen. We might use source-build, for instance, to produce each independent vertical and that would potentially be the primary way that Microsoft builds the binaries it distributes, but:
- The functionality is unlikely to make it back to older releases
- We have a long way to go.

You can be **sure** that we will be tooting a very loud horn if/when this happens. It's also highly likely that source-build functionality will be used to produce distro specific builds in a much nearer future.

@richlander @dleeapho for further comments and corrections.

**Comment by geekley** [comment] 2021-12-03 22:56
@mmitche 
Can I assume that if/when reproducibility is fully achieved, it'll be on a new major version, like .NET 7, .NET 8 etc? Not on .NET 6?
So I should watch for announcements on major versions?

**Comment by mmitche** [comment] 2021-12-03 23:00
> 

Yes, that will be for sure. The investment to drastically alter the engineering system usually takes place only on major version boundaries, since it's inherently a little risky, and is a huge undertaking.

**Comment by MichaelSimons** [comment] 2021-12-09 19:34
[Triage] Closing per mmitche's response.  @mmitche - Do you have an issue/epic tracking this at the broader dotnet organization?

**Closed by MichaelSimons** 2021-12-09 19:34 UTC
Labels: untriaged

**Comment by geekley** [comment] 2022-11-02 20:55
@mmitche I've noticed `dotnet6` is now included in Ubuntu's apt/deb `universe` repos since `22.04 jammy`. Is that an indication of .NET now being considered reproducible? I believe `universe` packages are always at least built completely from source, and independently, isn't?

**Comment by mmitche** [comment] 2022-11-07 22:31
@geekley Yes, Ubuntu builds those completely from source.

**Comment by omajid** [comment] 2022-11-17 22:44
I don't believe .NET is reproducible in the sense described at https://reproducible-builds.org/docs/definition/ yet. We can build .NET from source-only, and we can build it without network access, but repeating the build in the same environment doesn't produce bit-by-bit identical builds yet.

There is also an [effort to verify .NET builds (`.dll` files)](https://github.com/dotnet/designs/blob/main/accepted/2020/reproducible-builds.md) but even that's currently quite limited and doesn't work 100%.
