### ISSUE TITLE
CentOSStream9_Offline_MsftSdk_x64 build failing with `Object reference not set to an instance of an object.` error

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4485] opened 2024-06-28 09:57 UTC
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2484343&view=logs&j=27bc86d6-5b04-5e7e-1952-551ad1371b06&t=7de518f5-71d4-5df0-99bc-efa6e473f337) (internal Microsoft link):

        CSC : error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotHideBaseClassMethodsAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/vmr/src/vstest/src/Microsoft.TestPlatform.CoreUtilities/Microsoft.TestPlatform.CoreUtilities.csproj::TargetFramework=net9.0]
    ##[error]CSC(0,0): error AD0001: (NETCORE_ENGINEERING_TELEMETRY=Build) Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DoNotHideBaseClassMethodsAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Comment by ViktorHofer** [comment] 2024-06-28 14:02
Closing as duplicate of https://github.com/dotnet/source-build/issues/4451

**Closed by ViktorHofer** 2024-06-28 14:02 UTC
Labels: untriaged, ops-monitor
