### ISSUE TITLE
Add basic tests for PackageSourceGenerator in SBRP

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3343] opened 2023-03-27 09:57 UTC
In the past we have encountered trivial issues in SBRP caused by changes to the package source generator. Examples:
  - https://github.com/dotnet/source-build-reference-packages/pull/582
  - https://github.com/dotnet/source-build-reference-packages/pull/586

These could be safeguarded against with some basic tests that would executed as part of the CI thus validating any incoming changes before merge.

**Comment by ViktorHofer** [comment] 2023-03-27 10:04
Closing as duplicate of https://github.com/dotnet/source-build/issues/3089

**Closed by ViktorHofer** 2023-03-27 10:04 UTC
Labels: untriaged
