### ISSUE TITLE
Obsolete instructions for using a bootstrapped CLI

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/source-build#334] opened 2018-02-27 22:09 UTC
@janvorli The following instructions are out of date and not in the docs here.
```
Now that the bootstrap CLI works, it can be used to build coreclr, corefx and core-setup 
repos in its completeness, including the managed code. First set the `DOTNET_TOOL_DIR`
env variable to the path where the boostrap CLI is located. That will cause the build process
to use these tools instead of trying to download a `.tar.gz` package with OS specific tools 
from Azure.
```

Debugging CoreCLR, `init-tools.sh`, looks like `DotNetBuildToolsDir` is now the correct variable, but it also expects more than the CLI.

It assumes a full directory including a ful set of BUILD_TOOLS.

If I comment,
https://github.com/dotnet/coreclr/blob/master/init-tools.sh#L33-L36 .  I can work around some of those issues, but I get an error have trouble when the build tools init script is called.

**Comment by janvorli** [comment] 2018-02-27 22:24
There were changes that were made to the init-tools.sh that completely changed the way to plug in self-built copy of tools. That's the reason I've not finished that part of the doc yet - I need to go and figure out how to do that in the new world.

**Comment by sdmaclea** [comment] 2018-03-02 23:18
See https://github.com/dotnet/coreclr/pull/16709 for my solution.

**Comment by weshaggard** [comment] 2018-03-02 23:32
This is a duplicate of https://github.com/dotnet/source-build/issues/229. @sdmaclea thanks for adding support for this.

**Comment by kasper3** [comment] 2018-03-15 14:40
@sdmaclea, is the CoreCLR fix require follow-up changes in this repo?

**Comment by sdmaclea** [comment] 2018-03-15 15:48
CoreClr and CoreFX changes to init-tools are in place.  Core-setup PR needs to be written.

buildbootstrap documentation in this repo needs to be updated to explain how to use bootstrap cli.

**Comment by sdmaclea** [comment] 2018-03-15 17:46
Core-setup PR was just merged.

Only thing remains is documetation.  @janvorli original documentation in the original post is close, just a few of the fine details have changed.

**Comment by janvorli** [comment] 2018-03-15 18:04
@sdmaclea nice, I'll update the doc than.

**Comment by kasper3** [comment] 2018-03-15 18:15
@janvorli, is the ultimate goal is to produce a one big buildable tarball, even without having to connect to the internet? Package distributors are going to like it very much. :)

**Comment by janvorli** [comment] 2018-03-15 18:48
That's the ultimate goal of this repo. But my doc is kind of a side step. The part of my doc that's not in the repo yet describes how you can use the bootstrap CLI to build packages in coreclr, corefx and core-setup repos. That is useful until the build from sources works end to end.

**Comment by dseefeld** [comment] 2018-08-29 18:39
@janvorli Are there any other changes to doc that are required here?  Can this be closed?

**Comment by omajid** [comment] 2018-08-29 18:54
FYI I was able to use source-build to produce a portable build, then use bootstrap on that to build to target a new Linux distro, and then use source-build with that bootstrapped cli to build on the new Linux distro end-to-end.

**Closed** 2018-08-30 23:15 UTC
Labels: area-doc, triaged
