### ISSUE TITLE
Get core-setup versions from authoritative location instead of regex

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#554] opened 2018-05-16 18:38 UTC
See https://github.com/dotnet/source-build/pull/551#issuecomment-389597137.

We do not have a regex that works for all cases:
* 2.1.0
* 2.1.0-rc1
* 2.1.0-rc1-12345-67

And does not capture
* 2.1.0-ubuntu

A better approach is to get the version out of NuGet packages or some other authoritative location.

**Comment by dleeapho** [comment] 2018-05-16 19:42
Is this a dupe of #550 ?

**Comment by crummel** [comment] 2018-05-16 19:46
I don't think so.  #550 is for getting stabilization/version stamp status from ProdCon so we can match the official build's version numbers.  This is an issue in our `PublishCoreSetupBinaries` task where we don't have a good way to get the version numbers for assets that core-setup produced.  We could generate this version ourselves based on the stabilization/version stamp info from prodcon but I'm not sure we want to duplicate that code.

**Comment by dagood** [comment] 2018-05-16 20:58
Something to consider is having core-setup itself publish to the location we expect, and we just tell it the base dir. This is similar to how it works for ProdCon (although the code probably doesn't work right now with a file system).

**Comment by crummel** [comment] 2018-07-19 03:42
When this is fixed we should also remove `tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks/PublishToolsetBinaries.cs` as it is mostly duplicated code with a changed regex.

**Comment by MichaelSimons** [comment] 2022-10-14 18:43
[Triage] This issue is obsolete.  Source-build no longer uses this regex to retrieve the version number.

**Closed by MichaelSimons** 2022-10-14 18:43 UTC
Labels: area-build
