### ISSUE TITLE
Bootstrap stage 2 build failure in Microsoft.Build.Tasks.Git.LocateRepository task

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3399] opened 2023-04-19 19:51 UTC
```
/vmr/.dotnet/sdk/8.0.100-preview.4.23219.1/Sdks/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.targets(26,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.InvalidCastException: [A]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository] cannot be cast to [B]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository]. Type A originates from 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location '/vmr/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.4.23217.4/System.Private.CoreLib.dll'. Type B originates from 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location '/vmr/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.4.23217.4/System.Private.CoreLib.dll'.
   at Microsoft.Build.Tasks.Git.RepositoryTask.TryGetCachedRepositoryInstance(String cacheKey, Boolean requireCached, GitRepository& repository)
   at Microsoft.Build.Tasks.Git.RepositoryTask.GetOrCreateRepositoryInstance()
   at Microsoft.Build.Tasks.Git.RepositoryTask.ExecuteImpl()
   at Microsoft.Build.Tasks.Git.RepositoryTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/targetPacks/ILsrc/microsoft.netcore.app.ref/7.0.0/Microsoft.NETCore.App.Ref.7.0.0.csproj]
```

This occurs in the dependency project build of SBRP when attempting to build Microsoft.NETCore.App.Ref.7.0.0.

[Build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162297&view=results) (internal only)

**Comment by MichaelSimons** [comment] 2023-04-20 16:06
[Triage] The fix for https://github.com/dotnet/sdk/pull/31863 should have come in this morning so this should be fixed.

**Comment by MichaelSimons** [comment] 2023-04-20 22:50
This is still not resolved.

**Comment by MichaelSimons** [comment] 2023-04-21 01:02
It's possible the packages from prebuilts are causing this.  Removing them in https://github.com/dotnet/installer/pull/16176.

**Comment by MichaelSimons** [comment] 2023-04-21 02:48
> It's possible the packages from prebuilts are causing this. Removing them in [dotnet/installer#16176](https://github.com/dotnet/installer/pull/16176).

Unfortunately it didn't resolve the issue.

**Comment by mthalman** [comment] 2023-04-21 14:29
@tmat, @ViktorHofer - Could you help in determining the cause of this failure?

For context, this is failing in the bootstrap build workflow where we source-build the https://github.com/dotnet/dotnet repo once and then use the outputted SDK as the toolset to build the source again. It fails in that second build.

I've attached the build's binlog:
[sourcebuild-dependency-projects.zip](https://github.com/dotnet/source-build/files/11296537/sourcebuild-dependency-projects.zip)

What's odd about the exception message is that it's complaining that Type A can't be cast to Type B even though it reports that Type A and B are the same type from the same assembly file. I suspect that it's possible the message is actually wrong here given that it's a generic type and the real casting issue is with the `GitRepository` type. It doesn't indicate anything about that type's assembly in the error.

Here's the relevant code doing the cast: https://github.com/dotnet/dotnet/blob/e2903bde31921e07bebca58f03f6b1395dd74802/src/sourcelink/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs#L150

It's possible that use of an MSBuild registered task object is a factor here.

**Comment by mthalman** [comment] 2023-04-21 15:40
I took a shot in the dark and added a call to `dotnet build-server shutdown` right before this line: 

https://github.com/dotnet/dotnet/blob/e2903bde31921e07bebca58f03f6b1395dd74802/src/source-build-reference-packages/eng/Build.props#L181

But that made no difference.

**Comment by tmat** [comment] 2023-04-21 15:45
Seems like a dup: https://github.com/dotnet/sourcelink/issues/1007, https://github.com/dotnet/msbuild/issues/8478
@rainersigwald

**Comment by mthalman** [comment] 2023-04-21 15:54
@rainersigwald - Please work with @tmat / sourcelink folks to determine a fix or workaround for this. This is blocking the source-build release of 8.0 Preview 4.

**Comment by tmat** [comment] 2023-04-21 15:59
As a workaround I can add try-catch around the cache lookup. It will be a potential build perf issue, but not correctness issue.

**Comment by tmat** [comment] 2023-04-21 16:03
Here: https://github.com/dotnet/sourcelink/pull/1008

**Comment by tmat** [comment] 2023-04-21 16:18
I'm gonna close this issue as it should be addressed by the above workaround. Still keeping the msbuild issue opened to track the root cause.

**Comment by mthalman** [comment] 2023-04-21 16:45
I'd rather keep this open until our build is actually passing.

**Closed** 2023-04-21 18:07 UTC
Labels: area-ci-testing

**Comment by tmat** [comment] 2023-05-23 21:55
@mthalman 
The log https://github.com/dotnet/source-build/issues/3399#issuecomment-1517922022 shows there are two copies of Source Link assembly loaded to the build process:

![image](https://github.com/dotnet/source-build/assets/41759/010f12de-70aa-4cb2-b3e2-860fc1fcb6e8)

Is this expected?

**Comment by mthalman** [comment] 2023-05-24 12:59
I would think that's a possibility. It would be a scenario where a project has a compile-time dependency on Microsoft.Build.Tasks.Git _and_ the logic of the SDK has a runtime dependency on Microsoft.Build.Tasks.Git.

**Comment by rainersigwald** [comment] 2023-05-24 13:31
That shouldn't be a conflict; the compile-time dependency shouldn't be loaded by any part of MSBuild in a persistent way, while the SDK reference (UsingTask) would.

The log shows that the assembly is being loaded in the latter way from two different paths:

<img width="859" alt="image" src="https://github.com/dotnet/source-build/assets/3347530/f75a8346-75dd-465f-9fa4-1f36e2483be0">

This looks like it might be fallout from the temporary situation where that task is present both in the SDK and via package--and I'd expect the long-term fix to be that the package goes away and only the SDK copy is used in sourcebuild.
