### ISSUE TITLE
[SBRP] generate.sh fails with "DocIdKinds" parameter does not have a "set" accessor

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3084] opened 2022-10-24 15:55 UTC
When I run `./generate.sh --pkg <package>` from `main` or `release/7.0` it fails with the following error.

```
/root/.nuget/packages/microsoft.dotnet.genapi/7.0.0-beta.22166.1/build/Microsoft.DotNet.GenAPI.targets(56,7): error MSB4093: The "DocIdKinds" parameter of the "Microsoft.DotNet.GenAPI.GenAPITask" task cannot be written to because it does not have a "set" accessor. [/repos/source-build-reference-packages/src/referencePackageSourceGenerator/GenerateSource/GenerateSource.proj]
```

I have tried generating several different packages - some that are new and some that have already been generated.

system.console,4.3.0
microsoft.visualbasix,10.3.0
system.data.sqlclient,4.8.4

This is a blocking issue.  As a workaround, I was able to use the tooling from `release/6.0` and copy the output to `main` or `release/7.0`.

**Comment by MichaelSimons** [comment] 2022-10-24 15:56
@oleksandr-didyk - Can you take a look at this issue?

**Comment by oleksandr-didyk** [comment] 2022-10-25 10:43
It seems that [this](https://github.com/dotnet/source-build-reference-packages/commit/8366acfc3e0660ceef6bddbe7794044e5d503521#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfR6) Arcade SDK version bump introduced the issue, before that the generation process work as intended.

Looked into the changes introduced to GenAPI in the new Arcade SDK version and all of them were performed by @andriipatsula. I provided him with the binlogs and the DLLs used, he will investigate the problem and update the issue once there is some more info on it.

**Comment by andriipatsula** [comment] 2022-10-25 14:36
In `main` [this commit](https://github.com/dotnet/source-build-reference-packages/commit/1f8037df094f11e7ab0422cbe514726ccc920d78) have broken the SBRP generator (commit before works just fine). In contains updates in `eng/common` folder and updates for dotnet and arcade sdk versions (global.json). The arcade SDK from `7.0.0-beta.22411.2` -> `8.0.0-beta.22462.4` and dotnet from `7.0.100-preview.7.22377.5` -> `7.0.100-preview.5.22307.18`.

if I revert the arcade SDK version back to `7.0.0-beta.22411.2` and remove `.dotnet` folder and the problem still persists. 
If I revert both the arcade SDK version and dotnet version and remove `.dotnet` folder - the problem disappears.
If I revert just the dotnet version back to `7.0.100-preview.7.22377.5` and remove `.dotnet` folder - the problem disappears too.

I double check each scenario and I can't understand why we have this issue with newer version of dotnet. It is some bug or known issue? Does anyone here something about that?

I checked that GenAPI dll that is used by SBRB generator is valid (version `7.0.0-beta.22166.1`, created 16 of March, [link](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.GenAPI/overview/7.0.0-beta.22166.1)) and `ildasm` shows that it consist of MSBuild Task and properties.

**Comment by andriipatsula** [comment] 2022-10-25 14:55
This could be an issue of MSBuild in `preview.7`. I'll start a conversation with guys that works on MSBuild.

**Comment by andriipatsula** [comment] 2022-10-26 12:10
I had a conversation with @rokonec and we were able to reproduce this problem in fedora and ubuntu OSs. He's going to play with that a little bit and provide some conclusions.

**Comment by MichaelSimons** [comment] 2022-10-26 21:00
Have you tried with a later version of the SDK like RC2?

**Comment by andriipatsula** [comment] 2022-10-27 09:29
I tried dotnet version `7.0.100-rc.2.22477.23` and the problem still persist

Roman investigated a problem and said that the error is:
> Could not load file or assembly 'Microsoft.Cci.Extensions, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\n

I checked that `Microsoft.DotNet.GenAPI` is installed with `Microsoft.Cci.dll` and `Microsoft.Cci.Extensions.dll` libraries, so these symbols must be visible.

I am going to create an issue in `dotnet/MSBuild` repo to start a conversation.

**Comment by andriipatsula** [comment] 2022-10-27 09:48
I found the solution:
The GenAPI [version](https://github.com/dotnet/source-build-reference-packages/blob/328a67c872579620f27c722c30f5cdb123b32051/eng/Versions.props#L14) is specified [7.0.0-beta.22166.1](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.GenAPI/overview/7.0.0-beta.22166.1) (create in March 2022) and if you choose latest version like [8.0.0-beta.22526.10](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.GenAPI/overview/8.0.0-beta.22526.10) - the problem disappear. I expected that two GenAPI compiled with older version must run on newer one (due to backward compatibility). I'll create a PR to update the version of GenAPI for SBRP.

**Comment by andriipatsula** [comment] 2022-10-27 09:59
PR created [link](https://github.com/dotnet/source-build-reference-packages/pull/469).

**Comment by MichaelSimons** [comment] 2022-10-27 13:42
> I found the solution: The GenAPI [version](https://github.com/dotnet/source-build-reference-packages/blob/328a67c872579620f27c722c30f5cdb123b32051/eng/Versions.props#L14) is specified [7.0.0-beta.22166.1](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.GenAPI/overview/7.0.0-beta.22166.1) (create in March 2022) and if you choose latest version like [8.0.0-beta.22526.10](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.GenAPI/overview/8.0.0-beta.22526.10) - the problem disappear. I expected that GenAPI compiled with older version must run on newer version of dotnet (due to backward compatibility). I'll create a PR to update the version of GenAPI for SBRP.

This seem viable for fixing main but isn't an option for the release/7.0 branch.  The tooling needs to be fixed in both branches.

**Comment by andriipatsula** [comment] 2022-10-27 14:06
PR for `release/7.0` https://github.com/dotnet/source-build-reference-packages/pull/471

**Comment by andriipatsula** [comment] 2022-11-01 09:06
both PRs are merged

**Closed by andriipatsula** 2022-11-01 09:06 UTC
Labels: area-sbrp
