### ISSUE TITLE
Release pipeline should look up and verify the associated SDK diff run

### ISSUE THREAD

**Issue by premun** [dotnet/source-build#3297] opened 2023-03-03 14:57 UTC
### Context

There will be a new pipeline running the SDK diff test daily. The release steps require you to go and check the smoke test results. This is a manual step that can now be automated.

### Proposal

We can automate this by looking up the SDK diff pipeline run based on the installer SHA - all the code is already in place to look up pipelines, to verify their result and the pipeline will have the tag with the installer SHA.

Alternatively, we can just ask user to verify the test results at a given link (point to the pipeline) and let the user decide if the failures are blocking.

Alternatively, the user would re-run the release without "Verify associated pipeline runs" setting to ignore failures.

**Extra:**  
The release pipeline could also queue the SDK diff pipeline for a given SHA in case there's no run like that because it already has the ID of the VMR pipeline. Alternatively it can ask the user to run it.

**Comment by premun** [comment] 2023-03-03 15:02
@MichaelSimons we have a good chance to automate more manual steps of the release. It would probably also be possible to add the poison leak smoke tests to the SDK diff pipeline as those are other tests we manually check during the release.

Thoughts?

**Comment by MichaelSimons** [comment] 2023-03-03 15:13
We have made a lot of progress on the poison leaks in main and the desire is to have them fail the tests instead of warn by time we release.  Besides, the poison tests require a full build and therefore should stay in the main pipeline.

**Comment by premun** [comment] 2023-03-03 15:27
Regardless of the poison tests, should we look up the SDK diff pipeline in the associated runs part and require a run exists for the released VMR SHA (potentially require a pass?)?

**Comment by MichaelSimons** [comment] 2024-02-23 16:32
We are not guaranteed to have an SDK diff run because it runs on a schedule.  We have a few options:

1. Run the SDK diff on each commit in release branches so we are guaranteed to have a run
1. If an SDK diff run for the release commit doesn't exit, add a approval step requiring explicit signoff.
1. If an SDK diff run for the release commit doesn't exit, check the most recent run for the release branch

I list these in my preferred order.  @dotnet/source-build-internal for input.

**Comment by mthalman** [comment] 2024-02-23 16:45
My preference is `#1` as well. If this is important enough to be verifying, we should be verifying against the actual release commit.

**Comment by ellahathaway** [comment] 2024-02-23 16:46
If increasing the runs of the SDK diff does not significantly impact our computational resources, then I'm think #1 is the best choice. Otherwise, I think an approval step should exist in the pipeline. Checking the SDK diff results is currently a manual step in the release checklist, so I think it makes sense to transition to a step in the pipeline.

**Comment by oleksandr-didyk** [comment] 2024-02-23 18:01
I also agree with `#1` for the reason that Matt said - for a commit history of A -> B  -> C were we are releasing B having an SDK diff run for A and C but not B itself is not ideal.

Maybe its worth having the Stage-DotNet trigger the SDK run for the commit it is trying to release? That would limit us to only running the tests on a released commit (or expected to be released commit), making it available for the source-build release pipeline to check and limiting the amount of extra builds triggered

**Comment by MichaelSimons** [comment] 2024-02-23 18:06
>Maybe its worth having the Stage-DotNet set of pipelines trigger the SDK diff run for the commit it is trying to release? That would limit us to only running the tests on a released commit (or expected to be released commit), making it available for the source-build release pipeline to check without manual intervention and limiting the amount of extra builds triggered.

IMO we should keep is simple and run the pipeline for every release commit.  We want to flush out any regressions ASAP.  This pipeline does not require a significant amount of compute.

**Comment by oleksandr-didyk** [comment] 2024-02-23 18:08
Sure, then as part of this work I'll change the SDK diff pipeline to run for every commit in `release` and then have the source-build release pipeline check if that run passes. + adding a flag to skip the SDK diff pipeline check just in case

**Comment by oleksandr-didyk** [comment] 2024-03-07 15:33
PR for adding a ReleaseCLI command for fetching an AzDO pipeline run - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/37935

**Comment by oleksandr-didyk** [comment] 2024-03-28 14:55
PR for adding the check to the release pipeline - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/38599

**Comment by oleksandr-didyk** [comment] 2024-04-09 07:51
Waiting on the trigger change to flow into internal to verify it

**Comment by oleksandr-didyk** [comment] 2024-04-10 09:07
The change has flown in, but the pipeline was not triggered for the release runs. 

Looked into it, seems the triggers were overridden in UI. Fixed, tried to start runs manually, the SDK diff tests were triggered as expected.

Will wait for a few proper release builds to get triggered to be extra sure

**Comment by oleksandr-didyk** [comment] 2024-04-30 11:47
Trigger verified, closing

**Comment by ellahathaway** [comment] 2024-04-30 20:22
@oleksandr-didyk - I think that the tagging is slightly off. The release pipeline is looking for `installer <sha>` and the associated SDK diff run uses `installer-<sha>`.

**Comment by oleksandr-didyk** [comment] 2024-05-03 08:15
Oh, that's my bad. I'll take a look, thanks for pinging me on this!

**Comment by oleksandr-didyk** [comment] 2024-05-03 12:34
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39381

**Comment by oleksandr-didyk** [comment] 2024-05-03 13:38
> PR - [dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39381](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/39381)

After discussion in the PR, the team made a decision to change the tag on the SDK diff test pipeline run instead to make it consistent with other pipelines using a similar pattern (such as `dotnet-source-build`)

**Comment by oleksandr-didyk** [comment] 2024-05-03 15:29
PR merged, the SDK diff tests build tag should now match the one the release pipeline is looking for and follow the pattern used by the other pipelines

**Closed** 2024-05-03 15:28 UTC
Labels: area-release-infra
