### ISSUE TITLE
[ArPow] Produce tarball from the installer repo

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1506] opened 2020-02-24 20:04 UTC
As a preliminary step to source-build for 5.0 and eliminating the source-build repo, this moves most source-build functionality to core-sdk.
- Build source-build tarball from core-sdk
- Doesn't include transport package creation or consumption

**Comment by dagood** [comment] 2020-04-17 17:49
For future reference: https://github.com/dotnet/source-build/issues/1466 has some notes on cleanup that will need to happen to get this done, and the prototype branch.

**Comment by MichaelSimons** [comment] 2021-05-28 16:59
Closing this as it is a duplicate of https://github.com/dotnet/source-build/issues/2063

**Closed** 2021-05-28 17:25 UTC
Labels: area-build, area-infra
