### ISSUE TITLE
submodule source changes being ignored

### ISSUE THREAD

**Issue by iv2985** [dotnet/source-build#859] opened 2018-11-08 03:50 UTC
I would like some feedback or documentation on why the build is not including my source-code changes. I wanted to verify that I can run an application with a modified runtime and made a simple change to Dictionary.cs in both corefx and coreclr submodules - throwing an exception in the constructor. I committed the changes within corefx and coreclr and then committed the submodule changes to the source-build root repo. However, the built packages (clean.cmd -a && build.cmd) under bin\x64\Release\runtime do not appear to include my changes.

Running an example application from the dotnet/coreclr project that prints build info gave: 

```
 var coreAssemblyInfo = System.Diagnostics.FileVersionInfo.GetVersionInfo(typeof(object).Assembly.Location);
            Console.WriteLine($"Hello World from Core {coreAssemblyInfo.ProductVersion}");
            Console.WriteLine($"The location is {typeof(object).Assembly.Location}");
```

> @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: master @SrcCode: https://github.com/dotnet/coreclr/tree/39229d58944ce415108e1f6e59a4ab5c77e93226
> The location is C:\Users\<username>\.nuget\packages\runtime.win-x64.microsoft.netcore.app\3.0.0-preview1-27023-03\runtimes\win-x64\native\System.Private.CoreLib.dll

The binaries in the .nuget folder were overwritten via copy-paste of the build output. The dlab14-DDVSOWINAGE101 should be my own computer, but is not.

**Comment by dagood** [comment] 2018-11-08 15:34
Just in case you haven't seen it, we have a doc about producing a runtime with changes here: https://github.com/dotnet/source-build/tree/master/Documentation#building-a-custom-net-runtime. The steps you took do seem fine to me, though.

You're right, `dlab14-DDVSOWINAGE101` is one of the build agents that produces Microsoft builds, which means the Core-Setup package you're looking at bundled a Microsoft CoreCLR package rather than your build's.

Before looking at `.nuget`, I think looking at the source-build output directly would be best. (Copying over the build output should be simple, there are just enough NuGet caches that I want to be completely sure we're looking at root cause.)

If you can look in `bin/obj/x64/Release/blob-feed/packages` and extract these packages (just unzip), then provide the output of `version.txt`/`Microsoft.NETCore.App.versions.txt` in each, that should show where the flow failed:

* `runtime.*.Microsoft.NETCore.Runtime.CoreCLR.*.nupkg` (CoreCLR)
* `runtime.*.Microsoft.Private.CoreFx.NETCoreApp.*.nupkg` (CoreFX)
* `runtime.*.Microsoft.NETCore.App.*.nupkg` (Core-Setup)

Also, the source-build commit your build is based on might be helpful.

/cc @crummel (working on `master` recently)

**Comment by iv2985** [comment] 2018-11-09 07:45
**Update: I created a fresh source-build clone and proceeded as before with updates to corefx and coreclr dictionary.cs, commit, and commit the submodule pointer changes.**

Now the app just crashes
```
'test.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Users\###\.nuget\packages\runtime.win-x64.microsoft.netcore.app\3.0.0-preview1-27023-03\runtimes\win-x64\native\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[12944] retry_test.exe' has exited with code -2147450743 (0x80008089).
```

The dotnet host commit (9ea8...) matches that from core-setup of a nuget package version you asked me to locate.
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009697
 Commit:    7365786612

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009697\

Host (useful for support):
  Version: 3.0.0-preview1-27023-03
  Commit:  9ea8c26816
```

**The version info from the three nuget packages are:**
runtime.win-x64.Microsoft.NETCore.App.3.0.0-preview1-27023-03/Microsoft.NETCore.App.versions.txt
```
core-setup 9ea8c2681641d948560558fab081d04810ff0274
corefx 7245b96faaf399be1df7d6f6a4ce816bfb9b400b
dotnet/versions/corefx c9d4b5a7aa257afc6af7acbfd32f45eec3b48218
coreclr e56315102c3f6d31c92b02396abc2e5263f299d9
dotnet/versions/coreclr c9d4b5a7aa257afc6af7acbfd32f45eec3b48218
```

runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR.3.0.0-preview1-27014-03/version.txt
`e56315102c3f6d31c92b02396abc2e5263f299d9`

runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.4.6.0-preview1-27023-03/version.txt
`7245b96faaf399be1df7d6f6a4ce816bfb9b400b`


**The relevant source-build submodules are as follows:**
 ```
e56315102c3f6d31c92b02396abc2e5263f299d9 ../../../../../../src/coreclr (arm64drop-2-10808-ge56315102c)
 7245b96faaf399be1df7d6f6a4ce816bfb9b400b ../../../../../../src/corefx (System.Collections.Immutable-1.1.36-27205-g7245b96faa)
9ea8c2681641d948560558fab081d04810ff0274 src/core-setup (v2.0.1-1251-g9ea8c26)
```


**The root hash with my commit:**
```
###@####$git log -1
commit 68f935960defa650b78237f22585d2907ac04404 (HEAD -> master)
Author: ######
Date:   Thu Nov 8 20:08:46 2018 -0800

    add dummy change to verify custom build - make dictionary constructor throw an exception
```

**Comment by dagood** [comment] 2018-11-12 23:14
> do you think source-build is ready to support casual consumers or does this project still need significant stabilization?

I don't have an answer to this yet, apologies. Generally speaking, the `release/2.1` branch is stablest. But it doesn't support building on Windows, and dev flow is the same as `master` (no incremental builds).

For the crash, I suspect `master` on Windows builds a broken Runtime right now. The end-to-end validation we do for Linux in CI is based on a full SDK+Runtime build, and we are only able to build the Runtime on Windows right now. @crummel is going to try to repro the issue you're seeing specifically.

**Comment by crummel** [comment] 2018-11-13 17:32
Hi @iv2985, it looks like the hashes you're using are after the update of the build tools to Arcade, which is an issue I'm working on right now (https://github.com/dotnet/source-build/issues/844).  I'm actually currently working on a similar issue with the upgrade and packages not being picked up.  Did you make any other changes to the build to get it to work at all?

**Comment by dagood** [comment] 2018-11-29 16:48
I'm closing this for now. https://github.com/dotnet/source-build/issues/844 should get the submodules on more recent commits so it's clearer how to put custom changes on top of them, and it's not completely sure what the repro steps are for this specific problem. Let us know if there's more we can do.

> do you think source-build is ready to support casual consumers or does this project still need significant stabilization?

Looked at this again--I'm still not comfortable with the expectations behind the statement to give a standalone answer. Compared to "solo/isolated" development on CoreCLR, CoreFX, etc., it's much easier to break Source-Build, but the intent is for any dev to be able to clone and build source-build and get a usable product.

Building on Windows is generally a lower priority for us, but any problems that come up are bugs we want to fix. (Funnily enough, we did just recently add Windows builds (up to Core-Setup) to the `release/*` branches.)

**Closed by dagood** 2018-11-29 16:48 UTC
