### ISSUE TITLE
build-source-tarball.sh try download SDK, ignoring --with sdk option

### ISSUE THREAD

**Issue by lupin-de-mid** [dotnet/source-build#1769] opened 2020-09-25 10:01 UTC
I'm trying to build source tarball with already downloadded SDK

But it try to download SDK ignoring already founded
```
git status
HEAD detached at v3.1.108-SDK
nothing to commit, working tree clean
```
```
./build-source-tarball.sh ../tarbals_108/  --with-sdk /home/user/gitlab/libraries/net-bootstrap/ 
Using custom bootstrap SDK from '/home/user/gitlab/libraries/net-bootstrap/', version 3.1.106
Found bootstrap SDK 3.1.106, bootstrap Arcade 1.0.0-beta.19359.6
+++ dirname /home/user/gitlab/libraries/source-build/build.sh
++ cd -P /home/user/gitlab/libraries/source-build
++ pwd
+ scriptroot=/home/user/gitlab/libraries/source-build
+ '[' false == true ']'
++ date +%m%d%H%M%S
+ /home/user/gitlab/libraries/source-build/eng/common/build.sh --restore --build -c Release --warnaserror false /bl:/home/user/gitlab/libraries/source-build/artifacts/log/Debug/Build_0924162014.binlog /flp:v=diag /p:ArchiveDownloadedPackages=true /p:TarballRoot=/home/user/gitlab/libraries/tarbals_108 /p:PackSourceBuildTarball=true /bl:/home/user/gitlab/libraries/source-build/artifacts/log/Debug/BuildTarball_0924162014.binlog
Downloading 'https://dot.net/v1/dotnet-install.sh'
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.106/dotnet-sdk-3.1.106-linux-x64.tar.gz```

**Comment by dagood** [comment] 2020-09-25 14:59
I think this might have the same root cause as https://github.com/dotnet/source-build/issues/1711. We handle `--with-sdk` differently in different scripts, and I think there are issues in `build-source-tarball.sh`'s implementation.

You might be able to take an idea from https://src.fedoraproject.org/rpms/dotnet3.1/blob/master/f/build-dotnet-tarball, and use `build.sh` to do your tarball build. The `/p:ArchiveDownloadedPackages=true` parameter is what does most of the work:

```
./build.sh /p:ArchiveDownloadedPackages=true  /p:DownloadSourceBuildReferencePackagesTimeoutSeconds=100000 /p:DownloadSourceBuildReferencePackagesTimeoutSeconds=100000
./build-source-tarball.sh "${unmodified_tarball_name}" --skip-build
```

If you add `--with-sdk` to the first command, that may get handled by a better implementation of `--with-sdk`. Then, the `--skip-build` prevents `./build-source-tarball.sh` from trying to download an SDK again there.

Let me know if this workaround helps. (I do want to fix this for real at some point, though.)

**Comment by dseefeld** [comment] 2020-10-08 18:24
--with-sdk in build-source-tarball.sh is specification for the sdk to include in the tarball and is not being passed to build.sh when doing a production build.

**Comment by omajid** [comment] 2022-10-19 18:56
In .NET 6 and later, `build-source-tarball.sh` is gone, the sdk download is handled by `prep.sh` and the tarball's `./build.sh` accepts a `--with-sdk` option correctly. I think we can close this? I don't expect any changes in 3.1 in the few months before it reaches its end of Life.

**Closed** 2022-10-20 18:55 UTC
Labels: area-infra
