### ISSUE TITLE
SDK diffs from vstest

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4079] opened 2024-02-01 13:59 UTC
```diff
@@ -270,6 +270,207 @@ index ------------
 ./sdk/x.y.z/Containers/tasks/netx.y/MSBuild.dll
 ./sdk/x.y.z/Containers/tasks/netx.y/Newtonsoft.Json.dll
 ./sdk/x.y.z/Containers/tasks/netx.y/NuGet.Common.dll
@@ ------------ @@
 ./sdk/x.y.z/cs/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/cs/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/cs/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/cs/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/cs/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/cs/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/cs/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/cs/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/cs/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/cs/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/cs/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/cs/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/cs/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/cs/MSBuild.resources.dll
 ./sdk/x.y.z/cs/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/de/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/de/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/de/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/de/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/de/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/de/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/de/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/de/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/de/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/de/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/de/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/de/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/de/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/de/MSBuild.resources.dll
 ./sdk/x.y.z/de/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/es/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/es/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/es/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/es/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/es/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/es/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/es/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/es/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/es/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/es/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/es/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/es/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/es/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/es/MSBuild.resources.dll
 ./sdk/x.y.z/es/System.CommandLine.resources.dll
 ./sdk/x.y.z/es/vstest.console.resources.dll
 ./sdk/x.y.z/Extensions/
-./sdk/x.y.z/Extensions/cs/
-./sdk/x.y.z/Extensions/cs/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/cs/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/cs/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/cs/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/cs/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/de/
-./sdk/x.y.z/Extensions/de/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/de/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/de/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/de/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/de/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/es/
-./sdk/x.y.z/Extensions/es/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/es/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/es/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/es/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/es/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/fr/
-./sdk/x.y.z/Extensions/fr/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/fr/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/fr/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/fr/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/fr/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/it/
-./sdk/x.y.z/Extensions/it/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/it/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/it/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/it/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/it/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ja/
-./sdk/x.y.z/Extensions/ja/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/ja/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/ja/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/ja/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ja/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ko/
-./sdk/x.y.z/Extensions/ko/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/ko/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/ko/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/ko/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ko/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/Extensions/Microsoft.Diagnostics.NETCore.Client.dll
 ./sdk/x.y.z/Extensions/Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
 ./sdk/x.y.z/Extensions/Microsoft.TestPlatform.Extensions.EventLogCollector.dll
 ./sdk/x.y.z/Extensions/Microsoft.TestPlatform.TestHostRuntimeProvider.dll
 ./sdk/x.y.z/Extensions/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
 ./sdk/x.y.z/Extensions/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
-./sdk/x.y.z/Extensions/pl/
-./sdk/x.y.z/Extensions/pl/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/pl/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/pl/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/pl/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/pl/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/pt-BR/
-./sdk/x.y.z/Extensions/pt-BR/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/pt-BR/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/pt-BR/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/pt-BR/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/pt-BR/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ru/
-./sdk/x.y.z/Extensions/ru/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/ru/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/ru/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/ru/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/ru/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/tr/
-./sdk/x.y.z/Extensions/tr/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/tr/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/tr/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/tr/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/tr/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/zh-Hans/
-./sdk/x.y.z/Extensions/zh-Hans/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/zh-Hans/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/zh-Hans/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/zh-Hans/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/zh-Hans/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/zh-Hant/
-./sdk/x.y.z/Extensions/zh-Hant/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
-./sdk/x.y.z/Extensions/zh-Hant/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
-./sdk/x.y.z/Extensions/zh-Hant/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
-./sdk/x.y.z/Extensions/zh-Hant/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
-./sdk/x.y.z/Extensions/zh-Hant/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/fr/
 ./sdk/x.y.z/fr/dotnet.resources.dll
 ./sdk/x.y.z/fr/Microsoft.Build.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/fr/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/fr/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/fr/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/fr/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/fr/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/fr/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/fr/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/fr/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/fr/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/fr/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/fr/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/fr/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/fr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/fr/MSBuild.resources.dll
 ./sdk/x.y.z/fr/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/it/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/it/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/it/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/it/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/it/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/it/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/it/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/it/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/it/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/it/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/it/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/it/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/it/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/it/MSBuild.resources.dll
 ./sdk/x.y.z/it/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/ja/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/ja/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/ja/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/ja/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/ja/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/ja/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/ja/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/ja/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/ja/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/ja/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/ja/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/ja/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/ja/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/ja/MSBuild.resources.dll
 ./sdk/x.y.z/ja/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/ko/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/ko/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/ko/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/ko/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/ko/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/ko/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/ko/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/ko/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/ko/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/ko/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/ko/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/ko/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/ko/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/ko/MSBuild.resources.dll
 ./sdk/x.y.z/ko/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/Microsoft.Build.NuGetSdkResolver.dll
 ./sdk/x.y.z/Microsoft.Build.Tasks.Core.dll
@@ -278,6 +479,54 @@ index ------------
 ./sdk/x.y.z/Microsoft.Common.CrossTargeting.targets
 ./sdk/x.y.z/Microsoft.Common.CurrentVersion.targets
 ./sdk/x.y.z/Microsoft.Common.overridetasks
@@ ------------ @@
 ./sdk/x.y.z/pl/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/pl/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/pl/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/pl/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/pl/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/pl/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/pl/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/pl/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/pl/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/pl/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/pl/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/pl/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/pl/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/pl/MSBuild.resources.dll
 ./sdk/x.y.z/pl/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/pt-BR/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/pt-BR/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/pt-BR/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/pt-BR/MSBuild.resources.dll
 ./sdk/x.y.z/pt-BR/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/ru/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/ru/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/ru/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/ru/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/ru/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/ru/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/ru/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/ru/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/ru/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/ru/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/ru/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/ru/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/ru/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/ru/MSBuild.resources.dll
 ./sdk/x.y.z/ru/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/Sdks/Microsoft.NET.Sdk.WebAssembly/tools/
 ./sdk/x.y.z/Sdks/Microsoft.NET.Sdk.WebAssembly/tools/netx.y/
@@ -293,4 +542,52 @@ index ------------
-./sdk/x.y.z/TestHostNetFramework/
 ./sdk/x.y.z/tr/
 ./sdk/x.y.z/tr/dotnet.resources.dll
 ./sdk/x.y.z/tr/Microsoft.Build.resources.dll
No newline at end of file
 ./sdk/x.y.z/tr/Microsoft.Build.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/tr/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/tr/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/tr/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/tr/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/tr/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/tr/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/tr/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/tr/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/tr/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/tr/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/tr/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/tr/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/tr/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/tr/MSBuild.resources.dll
 ./sdk/x.y.z/tr/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/zh-Hans/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/zh-Hans/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/zh-Hans/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/zh-Hans/MSBuild.resources.dll
 ./sdk/x.y.z/zh-Hans/System.CommandLine.resources.dll
@@ ------------ @@
 ./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.CommunicationUtilities.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.CoreUtilities.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.CrossPlatEngine.resources.dll
+./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.Extensions.BlameDataCollector.resources.dll
+./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.Extensions.EventLogCollector.resources.dll
+./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.TestHostRuntimeProvider.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.Utilities.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.TestPlatform.VsTestConsole.TranslationLayer.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.VisualStudio.TestPlatform.Client.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.VisualStudio.TestPlatform.Common.resources.dll
+./sdk/x.y.z/zh-Hant/Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.resources.dll
+./sdk/x.y.z/zh-Hant/Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.resources.dll
 ./sdk/x.y.z/zh-Hant/Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
 ./sdk/x.y.z/zh-Hant/MSBuild.resources.dll
 ./sdk/x.y.z/zh-Hant/System.CommandLine.resources.dll
No newline at end of file

```

**Comment by MichaelSimons** [comment] 2024-02-01 17:34
Closing as a duplicate of https://github.com/dotnet/source-build/issues/3922

**Closed by MichaelSimons** 2024-02-01 17:34 UTC
Labels: untriaged, ops-monitor
