### ISSUE TITLE
Look into additional validation for produced outputs

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#4131] opened 2024-02-14 14:52 UTC
During the February release we discovered several issues with tags and some of the produced outputs (like `release.json`) and could've been caught before hand.

Maybe its worth investing into some additional validation at the end of the test/validation pipeline that would skim the produced outputs for some easy-to-catch issues, like empty or not expanded values. We already have unit tests covering some of the functionality that we have ported to the ReleaseCLI, but since we still use scripts / do substitutions from the pipeline, it might be worth the effort.

**Comment by MichaelSimons** [comment] 2024-02-15 17:47
[Triage] As part of this, we should ensure the artifacts are identical as much as possible between the partner and GH releases.

**Comment by MichaelSimons** [comment] 2024-05-23 16:36
[Triage]  Closing as a duplicate of https://github.com/dotnet/source-build/issues/4408.  Even though this issue was logged first, https://github.com/dotnet/source-build/issues/4408 has more detail.

**Closed by MichaelSimons** 2024-05-23 16:36 UTC
Labels: area-release-infra
