### ISSUE TITLE
razor-tooling SB intermediate has no packages within it.

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#3306] opened 2023-03-09 20:56 UTC
### Describe the Bug

The source build intermediate for the razor repo doesn't actually have any files within it. This causes prebuilts within the SDK repo.

### Steps to Reproduce

https://dev.azure.com/dnceng/internal/_build/results?buildId=2131122&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by MichaelSimons** [comment] 2023-03-09 21:00
@mmitche - This looks like a duplicate of https://github.com/dotnet/razor/issues/8332

**Closed** 2023-03-09 21:35 UTC
Labels: untriaged
