### ISSUE TITLE
Source-build tasks should use `System.Text.Json`

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4078] opened 2024-01-31 22:23 UTC
At least two tasks are not using System.Text.Json yet:
- `UpdateJson` - https://github.com/dotnet/installer/blob/main/src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/UpdateJson.cs
- `GetJsonAttributeValue` - added with https://github.com/dotnet/installer/pull/18478

Please fix.

**Comment by MichaelSimons** [comment] 2024-02-01 14:17
This is a duplicate of https://github.com/dotnet/source-build/issues/921

**Closed by MichaelSimons** 2024-02-01 14:17 UTC
Labels: untriaged, area-ci-testing
