### ISSUE TITLE
[Tracking] Arcade prebuilts

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#3985] opened 2024-01-18 16:58 UTC
The following prebuilts are being detected in arcade:

```
<Usage Id="Microsoft.Extensions.Configuration" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Configuration" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Configuration.Binder" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Configuration.Binder" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.DependencyInjection" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.DependencyInjection" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Internal.DependencyInjection.Testing/project.assets.json" IsDirectDependency="true" />
  <Usage Id="Microsoft.Extensions.Logging" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging.Configuration" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging.Configuration" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Logging.Console" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" IsDirectDependency="true" />
  <Usage Id="Microsoft.Extensions.Logging.Console" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Options" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Options" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Primitives" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
  <Usage Id="Microsoft.Extensions.Primitives" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.DotNet.Arcade.Sdk/project.assets.json" />
  <Usage Id="System.Diagnostics.DiagnosticSource" Version="9.0.0-alpha.1.24059.2" File="src/arcade/artifacts/buildObj/obj/Microsoft.Arcade.Common/project.assets.json" />
```

PSB tarball has been updated to include these prebuilts.

This is blocking https://github.com/dotnet/installer/pull/18173 and https://github.com/dotnet/source-build/issues/3665

**Comment by mthalman** [comment] 2024-01-18 17:02
This is a duplicate of https://github.com/dotnet/source-build/issues/3984. But it may be fine to keep this open to track the follow up work, since this [will likely happen again](https://github.com/dotnet/installer/pull/18290#issuecomment-1898704951).

**Comment by ellahathaway** [comment] 2024-01-18 17:04
Did not see https://github.com/dotnet/source-build/issues/3984. This also relates to https://github.com/dotnet/installer/pull/18173, so I'd like to keep it open for tracking.

**Comment by ellahathaway** [comment] 2024-01-18 23:16
Currently investigating why these prebuilts are only being detected in the VMR and not at the repo level.

**Closed** 2024-01-19 00:54 UTC
Labels: untriaged, ops-monitor
