### ISSUE TITLE
Improvements for partner handoff for .NET 8.0.103/8.0.3

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#4120] opened 2024-02-13 21:32 UTC
I noticed a few things in the contents of the .NET 8.0.102/8.0.2 release. Could we improve these for the next release?

- `release.json` has the literal text "$(PUBLIC_VMR)". This should be `https://github.com/dotnet/dotnet` instead, right?

- release.json has a tag without the `v` prefix. All the tags on github.com use a `v prefix. This sounds like it's already captured by https://github.com/dotnet/source-build/issues/4052 too.

- Could we make the tarball name match [GitHub](https://github.com/dotnet/dotnet/archive/refs/tags/v8.0.1.tar.gz)? GitHub uses `dotnet-${tag_without_v}.tar.gz`, eg, `dotnet-8.0.1.tar.gz`.

- Could we put tarball contents in a directory named `dotnet-$tag_without_v/` (eg, `dotnet-8.0.2/`) like a download from GitHub?

**Comment by oleksandr-didyk** [comment] 2024-02-14 14:39
Hey Omair, thanks for the issue and I apologize for the inconvenience caused by the issues with the tag and `release.json`

  - the tag missing `v` prefix has been fixed and merged, should be properly set for March release onwards
  - the `release.json` having the incorrect repo link is an unfortunate result of a rebase where one of the variables in our pipeline was lost, causing the missing replacement. I'll log an issue for fixing it and adding some validation for the manifest files we produce to make we don't run into something like in the future

**Comment by omajid** [comment] 2024-04-24 15:41
I believe all of these issues have been fixed now. Can we close this?

**Closed** 2024-04-24 15:46 UTC
Labels: area-release-infra
