### ISSUE TITLE
`error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant` when using `PublicSign=true`

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#3240] opened 2023-02-09 22:01 UTC
### Describe the Bug

After a local hack to work around https://github.com/dotnet/arcade/issues/12515 and enable `PublicSign=true`, building source-build-reference-packages fails with this error:

```
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(54,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(55,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(56,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(57,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(58,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(59,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(60,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(61,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
```

Anyone know what this is and why this only happens when `PublicSign` is `true`? 

### Steps to Reproduce

```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
$ env | grep OPENSSL
$ rpm -qa | grep openssl
openssl-pkcs11-0.4.11-7.el9.x86_64
openssl-libs-3.0.1-43.el9_0.x86_64
openssl-3.0.1-43.el9_0.x86_64
openssl-devel-3.0.1-43.el9_0.x86_64
$ git remote -v
origin  https://github.com/dotnet/source-build-reference-packages (fetch)
origin  https://github.com/dotnet/source-build-reference-packages (push)
$ git rev-parse HEAD
d4e3afbde90f26eed821531c620604f47e75e859
$ ./build.sh
...
 # build fails with Interop+Crypto+OpenSslCryptographicException
$ vi /home/dotnet/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23103.1/tools/StrongName.targets
 # Change all `<PublicSign>false</PublicSign>` to `<PublicSign>true</PublicSign>`
$ ./build.sh
```

**Comment by MichaelSimons** [comment] 2023-02-09 22:38
@omajid - what commit are you building from and what previous source-build artifacts are you using?  I encountered this very error a few weeks ago and it was related to the previous source-build artifacts I was using.

**Comment by omajid** [comment] 2023-02-09 22:51
So this is just building source-build-reference-packages repo in the default configuration using `./build.sh`. This isn't part of a source-build build or the VMR build or even with `-sb` flags. Just `source-build-reference-packages` repoat commit `d4e3afbde90f26eed821531c620604f47e75e859` built with `./build.sh` on RHEL 9.

**Comment by MichaelSimons** [comment] 2023-02-09 23:09
Did you try building with `-sb`?  Building SBRP in any other way is not something tested.

**Comment by omajid** [comment] 2023-02-09 23:45
I tried, but I don't know how to bypass https://github.com/dotnet/arcade/issues/12515 by patching the `StrongName.targets` file in in source-build mode :( Any ideas?

**Comment by MichaelSimons** [comment] 2023-02-16 17:20
[Triage] Because building this repo in any other mode besides SB, reproducing/validating this in a SB configuration is blocked on a fix from https://github.com/dotnet/arcade/issues/12515.  Leaving untriaged.

**Comment by omajid** [comment] 2023-03-08 22:53
SBRP has now picked up https://github.com/dotnet/arcade/issues/12515.

This is the patch I am testing:

```
diff --git a/src/referencePackages/Directory.Build.props b/src/referencePackages/Directory.Build.props
index d2543753..a1227b20 100644
--- a/src/referencePackages/Directory.Build.props
+++ b/src/referencePackages/Directory.Build.props
@@ -25,6 +25,7 @@
     <KeyFileDir>$(RepoRoot)src/referencePackages/snk/</KeyFileDir>
     <SignAssembly>true</SignAssembly>
     <PublicSign>true</PublicSign>
+    <FullAssemblySigningSupported>false</FullAssemblySigningSupported>
 
     <StrongNameKeyId>Microsoft</StrongNameKeyId>
 
```


`./build.sh` fails with

```
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(54,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(55,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]                                                           /home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(56,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(57,78): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(58,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]                                                           
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(59,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(60,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]                                                           
/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/lib/netstandard2.0/Microsoft.Extensions.Logging.cs(61,82): error CS3024: Constraint type 'ILoggerProvider' is not CLS-compliant [/home/dotnet/source-build-reference-packages/src/referencePackages/src/microsoft.extensions.logging/2.1.1/Microsoft.Extensions.Logging.2.1.1.csproj::TargetFramework=netstandard2.0]   
```

But `./build.sh -sb` works fine:

```
...
  Building intermediate nupkg...
  Successfully created package '/home/dotnet/source-build-reference-packages/artifacts/packages/Release/NonShipping/Microsoft.SourceBuild.Intermediate.source-build-reference-packages.8.0.0-dev.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:03:12.77
```

Since `-sb` is the only supported mode, I guess there's nothing to do here.

**Comment by MichaelSimons** [comment] 2023-03-09 17:19
[Triage] https://github.com/dotnet/source-build/issues/3044 tracks the work to make SBRP always build in the source-build configuration.  Closing as we don't support any other build configuration.

**Closed by MichaelSimons** 2023-03-09 17:19 UTC
Labels: area-prebuilt-reduction, untriaged
