### ISSUE TITLE
Remove full-framework builds from source-build

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#2939] opened 2022-07-08 19:56 UTC
Now that Omnisharp is compatible with .NET Core we should be able to remove all the full-fx TargetFrameworks from source-built repos.

**Comment by MichaelSimons** [comment] 2022-07-21 18:14
This is a duplicate of https://github.com/dotnet/source-build/issues/2901

**Closed by MichaelSimons** 2022-07-21 18:14 UTC
Labels: area-build, untriaged
