### ISSUE TITLE
Baseline 2.1 prebuilt packages and allow comparison with master

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#630] opened 2018-07-06 20:12 UTC
- [ ] Get a baseline of the prebuilt packages for our latest shipped release
- [ ] Verify that the list of packages is sensible
- [ ] Come up with a (preferably automated) process to compare baseline with a new build

**Comment by dagood** [comment] 2018-07-08 20:14
Automating is already tracked by https://github.com/dotnet/source-build/issues/493.

**Comment by dseefeld** [comment] 2018-08-21 20:19
Duplicate of #493

**Closed** 2018-08-21 20:20 UTC
Labels: area-build
