### ISSUE TITLE
second build failed

### ISSUE THREAD

**Issue by sunny868** [dotnet/source-build#1762] opened 2020-09-23 03:07 UTC
First I run :
`./build.sh -c Release`
then builed success. And I  run top command again, but failed:
```
 [03:02:41.03] Building 'sourcelink'...done
/source-build/repos/Directory.Build.targets(369,5): error : sourcelink produced no new source-built package identities. Known possible causes: [/source-build/repos/sourcelink.proj]
/source-build/repos/Directory.Build.targets(369,5): error : ^ There may have been a silent failure in the submodule build. To confirm, check the build log file for undetected errors that may have prevented package creation: /source-build/artifacts/logs/sourcelink.log [/source-build/repos/sourcelink.proj]
/source-build/repos/Directory.Build.targets(369,5): error : ^ This error might be a false positive if sourcelink intentionally builds no nuget packages. If so, set the SkipEnsurePackagesCreated property to true in /source-build/repos/sourcelink.proj [/source-build/repos/sourcelink.proj]
/source-build/repos/Directory.Build.targets(369,5): error : ^ The 'bin' directory might be dirty from a previous build and the package files already existed. If so, perform a clean build, or check which packages were already in 'bin' by opening /source-build/artifacts/obj/x64/Release/PackageVersions.props.pre.sourcelink.xml [/source-build/repos/sourcelink.proj]
/source-build/repos/Directory.Build.targets(369,5): error : ^ The packages may have been written to an unexpected directory. For example, some repos used bin/ and changed to artifacts/ to match Arcade. Check PackagesOutput in /source-build/repos/sourcelink.proj (currently '/source-build/artifacts/src/sourcelink.f175b06862f889474b689a57527e489101c774cc/artifacts/packages/Release/Shipping/') [/source-build/repos/sourcelink.proj]
  'known-good' failed during build.

Build FAILED.
```

**Comment by dagood** [comment] 2020-09-23 15:08
This is expected, unfortunately. This part of that error message is meant to let you know you need to do a clean build:

> ^ The 'bin' directory might be dirty from a previous build and the package files already existed. If so, perform a clean build [...]

I think deleting `artifacts/` is normally enough to start clean, but `git clean -xdf` is the ultimate clean.

Lack of a good incremental build is one of the developer experience issues we're talking about here in the repo readme:

> A secondary goal of source-build is to allow .NET Core contributors to build a .NET Core SDK with coordinated changes in multiple repositories. However, the developer experience is significantly better in individual repositories and, if possible, contributors should make and test changes in the target repo, not source-build.

We have a plan to make incremental builds work better in the future at https://github.com/dotnet/source-build/issues/928. We do have a small part of it completed with https://github.com/dotnet/source-build/pull/1700, but I don't know if your build has that change (no commit hash or branch mentioned). That PR is intended to stop `sourcelink` from building if you run the root `build.sh` again when `sourcelink` already been built, but depending on what you're trying to do, that might not be what you want.

I'm closing this as a duplicate, but do feel free to ask more questions or chat on the gitter channel (in readme). 🙂

**Comment by dagood** [comment] 2020-09-23 15:08
Duplicate of https://github.com/dotnet/source-build/issues/928

**Closed by dagood** 2020-09-23 15:08 UTC
